// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: qorechain/rdk/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "qorechain.rdk.v1";

export interface MsgCreateRollup {
  creator: string;
  rollupId: string;
  profile: string;
  vmType: string;
  stakeAmount: string;
}

export interface MsgCreateRollupResponse {
  rollupId: string;
}

export interface MsgSubmitBatch {
  sequencer: string;
  rollupId: string;
  batchIndex: string;
  stateRoot: Uint8Array;
  prevStateRoot: Uint8Array;
  txCount: string;
  dataHash: Uint8Array;
  proof: Uint8Array;
}

export interface MsgSubmitBatchResponse {
}

export interface MsgChallengeBatch {
  challenger: string;
  rollupId: string;
  batchIndex: string;
  proof: Uint8Array;
}

export interface MsgChallengeBatchResponse {
}

export interface MsgResolveChallenge {
  resolver: string;
  rollupId: string;
  batchIndex: string;
  /**
   * fraud_upheld true: fraud confirmed -> batch rejected, challenger refunded +
   * rewarded from rollup stake. false: challenge dismissed -> challenger bond
   * forfeited to the rollup operator, batch eligible for finalization.
   */
  fraudUpheld: boolean;
}

export interface MsgResolveChallengeResponse {
}

export interface MsgPauseRollup {
  creator: string;
  rollupId: string;
  reason: string;
}

export interface MsgPauseRollupResponse {
}

export interface MsgResumeRollup {
  creator: string;
  rollupId: string;
}

export interface MsgResumeRollupResponse {
}

export interface MsgStopRollup {
  creator: string;
  rollupId: string;
}

export interface MsgStopRollupResponse {
}

function createBaseMsgCreateRollup(): MsgCreateRollup {
  return { creator: "", rollupId: "", profile: "", vmType: "", stakeAmount: "0" };
}

export const MsgCreateRollup: MessageFns<MsgCreateRollup> = {
  encode(message: MsgCreateRollup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.rollupId !== "") {
      writer.uint32(18).string(message.rollupId);
    }
    if (message.profile !== "") {
      writer.uint32(26).string(message.profile);
    }
    if (message.vmType !== "") {
      writer.uint32(34).string(message.vmType);
    }
    if (message.stakeAmount !== "0") {
      writer.uint32(40).int64(message.stakeAmount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateRollup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateRollup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.profile = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.vmType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.stakeAmount = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateRollup {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
      profile: isSet(object.profile) ? globalThis.String(object.profile) : "",
      vmType: isSet(object.vmType)
        ? globalThis.String(object.vmType)
        : isSet(object.vm_type)
        ? globalThis.String(object.vm_type)
        : "",
      stakeAmount: isSet(object.stakeAmount)
        ? globalThis.String(object.stakeAmount)
        : isSet(object.stake_amount)
        ? globalThis.String(object.stake_amount)
        : "0",
    };
  },

  toJSON(message: MsgCreateRollup): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    if (message.profile !== "") {
      obj.profile = message.profile;
    }
    if (message.vmType !== "") {
      obj.vmType = message.vmType;
    }
    if (message.stakeAmount !== "0") {
      obj.stakeAmount = message.stakeAmount;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgCreateRollup>): MsgCreateRollup {
    return MsgCreateRollup.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgCreateRollup>): MsgCreateRollup {
    const message = createBaseMsgCreateRollup();
    message.creator = object.creator ?? "";
    message.rollupId = object.rollupId ?? "";
    message.profile = object.profile ?? "";
    message.vmType = object.vmType ?? "";
    message.stakeAmount = object.stakeAmount ?? "0";
    return message;
  },
};

function createBaseMsgCreateRollupResponse(): MsgCreateRollupResponse {
  return { rollupId: "" };
}

export const MsgCreateRollupResponse: MessageFns<MsgCreateRollupResponse> = {
  encode(message: MsgCreateRollupResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rollupId !== "") {
      writer.uint32(10).string(message.rollupId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCreateRollupResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCreateRollupResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCreateRollupResponse {
    return {
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
    };
  },

  toJSON(message: MsgCreateRollupResponse): unknown {
    const obj: any = {};
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgCreateRollupResponse>): MsgCreateRollupResponse {
    return MsgCreateRollupResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgCreateRollupResponse>): MsgCreateRollupResponse {
    const message = createBaseMsgCreateRollupResponse();
    message.rollupId = object.rollupId ?? "";
    return message;
  },
};

function createBaseMsgSubmitBatch(): MsgSubmitBatch {
  return {
    sequencer: "",
    rollupId: "",
    batchIndex: "0",
    stateRoot: new Uint8Array(0),
    prevStateRoot: new Uint8Array(0),
    txCount: "0",
    dataHash: new Uint8Array(0),
    proof: new Uint8Array(0),
  };
}

export const MsgSubmitBatch: MessageFns<MsgSubmitBatch> = {
  encode(message: MsgSubmitBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sequencer !== "") {
      writer.uint32(10).string(message.sequencer);
    }
    if (message.rollupId !== "") {
      writer.uint32(18).string(message.rollupId);
    }
    if (message.batchIndex !== "0") {
      writer.uint32(24).uint64(message.batchIndex);
    }
    if (message.stateRoot.length !== 0) {
      writer.uint32(34).bytes(message.stateRoot);
    }
    if (message.prevStateRoot.length !== 0) {
      writer.uint32(42).bytes(message.prevStateRoot);
    }
    if (message.txCount !== "0") {
      writer.uint32(48).uint64(message.txCount);
    }
    if (message.dataHash.length !== 0) {
      writer.uint32(58).bytes(message.dataHash);
    }
    if (message.proof.length !== 0) {
      writer.uint32(66).bytes(message.proof);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitBatch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sequencer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.batchIndex = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.stateRoot = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.prevStateRoot = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.txCount = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.dataHash = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.proof = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitBatch {
    return {
      sequencer: isSet(object.sequencer) ? globalThis.String(object.sequencer) : "",
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
      batchIndex: isSet(object.batchIndex)
        ? globalThis.String(object.batchIndex)
        : isSet(object.batch_index)
        ? globalThis.String(object.batch_index)
        : "0",
      stateRoot: isSet(object.stateRoot)
        ? bytesFromBase64(object.stateRoot)
        : isSet(object.state_root)
        ? bytesFromBase64(object.state_root)
        : new Uint8Array(0),
      prevStateRoot: isSet(object.prevStateRoot)
        ? bytesFromBase64(object.prevStateRoot)
        : isSet(object.prev_state_root)
        ? bytesFromBase64(object.prev_state_root)
        : new Uint8Array(0),
      txCount: isSet(object.txCount)
        ? globalThis.String(object.txCount)
        : isSet(object.tx_count)
        ? globalThis.String(object.tx_count)
        : "0",
      dataHash: isSet(object.dataHash)
        ? bytesFromBase64(object.dataHash)
        : isSet(object.data_hash)
        ? bytesFromBase64(object.data_hash)
        : new Uint8Array(0),
      proof: isSet(object.proof) ? bytesFromBase64(object.proof) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgSubmitBatch): unknown {
    const obj: any = {};
    if (message.sequencer !== "") {
      obj.sequencer = message.sequencer;
    }
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    if (message.batchIndex !== "0") {
      obj.batchIndex = message.batchIndex;
    }
    if (message.stateRoot.length !== 0) {
      obj.stateRoot = base64FromBytes(message.stateRoot);
    }
    if (message.prevStateRoot.length !== 0) {
      obj.prevStateRoot = base64FromBytes(message.prevStateRoot);
    }
    if (message.txCount !== "0") {
      obj.txCount = message.txCount;
    }
    if (message.dataHash.length !== 0) {
      obj.dataHash = base64FromBytes(message.dataHash);
    }
    if (message.proof.length !== 0) {
      obj.proof = base64FromBytes(message.proof);
    }
    return obj;
  },

  create(base?: DeepPartial<MsgSubmitBatch>): MsgSubmitBatch {
    return MsgSubmitBatch.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgSubmitBatch>): MsgSubmitBatch {
    const message = createBaseMsgSubmitBatch();
    message.sequencer = object.sequencer ?? "";
    message.rollupId = object.rollupId ?? "";
    message.batchIndex = object.batchIndex ?? "0";
    message.stateRoot = object.stateRoot ?? new Uint8Array(0);
    message.prevStateRoot = object.prevStateRoot ?? new Uint8Array(0);
    message.txCount = object.txCount ?? "0";
    message.dataHash = object.dataHash ?? new Uint8Array(0);
    message.proof = object.proof ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgSubmitBatchResponse(): MsgSubmitBatchResponse {
  return {};
}

export const MsgSubmitBatchResponse: MessageFns<MsgSubmitBatchResponse> = {
  encode(_: MsgSubmitBatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitBatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitBatchResponse {
    return {};
  },

  toJSON(_: MsgSubmitBatchResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgSubmitBatchResponse>): MsgSubmitBatchResponse {
    return MsgSubmitBatchResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgSubmitBatchResponse>): MsgSubmitBatchResponse {
    const message = createBaseMsgSubmitBatchResponse();
    return message;
  },
};

function createBaseMsgChallengeBatch(): MsgChallengeBatch {
  return { challenger: "", rollupId: "", batchIndex: "0", proof: new Uint8Array(0) };
}

export const MsgChallengeBatch: MessageFns<MsgChallengeBatch> = {
  encode(message: MsgChallengeBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.challenger !== "") {
      writer.uint32(10).string(message.challenger);
    }
    if (message.rollupId !== "") {
      writer.uint32(18).string(message.rollupId);
    }
    if (message.batchIndex !== "0") {
      writer.uint32(24).uint64(message.batchIndex);
    }
    if (message.proof.length !== 0) {
      writer.uint32(34).bytes(message.proof);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgChallengeBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgChallengeBatch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.challenger = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.batchIndex = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.proof = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgChallengeBatch {
    return {
      challenger: isSet(object.challenger) ? globalThis.String(object.challenger) : "",
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
      batchIndex: isSet(object.batchIndex)
        ? globalThis.String(object.batchIndex)
        : isSet(object.batch_index)
        ? globalThis.String(object.batch_index)
        : "0",
      proof: isSet(object.proof) ? bytesFromBase64(object.proof) : new Uint8Array(0),
    };
  },

  toJSON(message: MsgChallengeBatch): unknown {
    const obj: any = {};
    if (message.challenger !== "") {
      obj.challenger = message.challenger;
    }
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    if (message.batchIndex !== "0") {
      obj.batchIndex = message.batchIndex;
    }
    if (message.proof.length !== 0) {
      obj.proof = base64FromBytes(message.proof);
    }
    return obj;
  },

  create(base?: DeepPartial<MsgChallengeBatch>): MsgChallengeBatch {
    return MsgChallengeBatch.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgChallengeBatch>): MsgChallengeBatch {
    const message = createBaseMsgChallengeBatch();
    message.challenger = object.challenger ?? "";
    message.rollupId = object.rollupId ?? "";
    message.batchIndex = object.batchIndex ?? "0";
    message.proof = object.proof ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgChallengeBatchResponse(): MsgChallengeBatchResponse {
  return {};
}

export const MsgChallengeBatchResponse: MessageFns<MsgChallengeBatchResponse> = {
  encode(_: MsgChallengeBatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgChallengeBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgChallengeBatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgChallengeBatchResponse {
    return {};
  },

  toJSON(_: MsgChallengeBatchResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgChallengeBatchResponse>): MsgChallengeBatchResponse {
    return MsgChallengeBatchResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgChallengeBatchResponse>): MsgChallengeBatchResponse {
    const message = createBaseMsgChallengeBatchResponse();
    return message;
  },
};

function createBaseMsgResolveChallenge(): MsgResolveChallenge {
  return { resolver: "", rollupId: "", batchIndex: "0", fraudUpheld: false };
}

export const MsgResolveChallenge: MessageFns<MsgResolveChallenge> = {
  encode(message: MsgResolveChallenge, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.resolver !== "") {
      writer.uint32(10).string(message.resolver);
    }
    if (message.rollupId !== "") {
      writer.uint32(18).string(message.rollupId);
    }
    if (message.batchIndex !== "0") {
      writer.uint32(24).uint64(message.batchIndex);
    }
    if (message.fraudUpheld !== false) {
      writer.uint32(32).bool(message.fraudUpheld);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgResolveChallenge {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgResolveChallenge();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.resolver = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.batchIndex = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.fraudUpheld = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgResolveChallenge {
    return {
      resolver: isSet(object.resolver) ? globalThis.String(object.resolver) : "",
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
      batchIndex: isSet(object.batchIndex)
        ? globalThis.String(object.batchIndex)
        : isSet(object.batch_index)
        ? globalThis.String(object.batch_index)
        : "0",
      fraudUpheld: isSet(object.fraudUpheld)
        ? globalThis.Boolean(object.fraudUpheld)
        : isSet(object.fraud_upheld)
        ? globalThis.Boolean(object.fraud_upheld)
        : false,
    };
  },

  toJSON(message: MsgResolveChallenge): unknown {
    const obj: any = {};
    if (message.resolver !== "") {
      obj.resolver = message.resolver;
    }
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    if (message.batchIndex !== "0") {
      obj.batchIndex = message.batchIndex;
    }
    if (message.fraudUpheld !== false) {
      obj.fraudUpheld = message.fraudUpheld;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgResolveChallenge>): MsgResolveChallenge {
    return MsgResolveChallenge.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgResolveChallenge>): MsgResolveChallenge {
    const message = createBaseMsgResolveChallenge();
    message.resolver = object.resolver ?? "";
    message.rollupId = object.rollupId ?? "";
    message.batchIndex = object.batchIndex ?? "0";
    message.fraudUpheld = object.fraudUpheld ?? false;
    return message;
  },
};

function createBaseMsgResolveChallengeResponse(): MsgResolveChallengeResponse {
  return {};
}

export const MsgResolveChallengeResponse: MessageFns<MsgResolveChallengeResponse> = {
  encode(_: MsgResolveChallengeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgResolveChallengeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgResolveChallengeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgResolveChallengeResponse {
    return {};
  },

  toJSON(_: MsgResolveChallengeResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgResolveChallengeResponse>): MsgResolveChallengeResponse {
    return MsgResolveChallengeResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgResolveChallengeResponse>): MsgResolveChallengeResponse {
    const message = createBaseMsgResolveChallengeResponse();
    return message;
  },
};

function createBaseMsgPauseRollup(): MsgPauseRollup {
  return { creator: "", rollupId: "", reason: "" };
}

export const MsgPauseRollup: MessageFns<MsgPauseRollup> = {
  encode(message: MsgPauseRollup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.rollupId !== "") {
      writer.uint32(18).string(message.rollupId);
    }
    if (message.reason !== "") {
      writer.uint32(26).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgPauseRollup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgPauseRollup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgPauseRollup {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: MsgPauseRollup): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgPauseRollup>): MsgPauseRollup {
    return MsgPauseRollup.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgPauseRollup>): MsgPauseRollup {
    const message = createBaseMsgPauseRollup();
    message.creator = object.creator ?? "";
    message.rollupId = object.rollupId ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseMsgPauseRollupResponse(): MsgPauseRollupResponse {
  return {};
}

export const MsgPauseRollupResponse: MessageFns<MsgPauseRollupResponse> = {
  encode(_: MsgPauseRollupResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgPauseRollupResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgPauseRollupResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgPauseRollupResponse {
    return {};
  },

  toJSON(_: MsgPauseRollupResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgPauseRollupResponse>): MsgPauseRollupResponse {
    return MsgPauseRollupResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgPauseRollupResponse>): MsgPauseRollupResponse {
    const message = createBaseMsgPauseRollupResponse();
    return message;
  },
};

function createBaseMsgResumeRollup(): MsgResumeRollup {
  return { creator: "", rollupId: "" };
}

export const MsgResumeRollup: MessageFns<MsgResumeRollup> = {
  encode(message: MsgResumeRollup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.rollupId !== "") {
      writer.uint32(18).string(message.rollupId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgResumeRollup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgResumeRollup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgResumeRollup {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
    };
  },

  toJSON(message: MsgResumeRollup): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgResumeRollup>): MsgResumeRollup {
    return MsgResumeRollup.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgResumeRollup>): MsgResumeRollup {
    const message = createBaseMsgResumeRollup();
    message.creator = object.creator ?? "";
    message.rollupId = object.rollupId ?? "";
    return message;
  },
};

function createBaseMsgResumeRollupResponse(): MsgResumeRollupResponse {
  return {};
}

export const MsgResumeRollupResponse: MessageFns<MsgResumeRollupResponse> = {
  encode(_: MsgResumeRollupResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgResumeRollupResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgResumeRollupResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgResumeRollupResponse {
    return {};
  },

  toJSON(_: MsgResumeRollupResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgResumeRollupResponse>): MsgResumeRollupResponse {
    return MsgResumeRollupResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgResumeRollupResponse>): MsgResumeRollupResponse {
    const message = createBaseMsgResumeRollupResponse();
    return message;
  },
};

function createBaseMsgStopRollup(): MsgStopRollup {
  return { creator: "", rollupId: "" };
}

export const MsgStopRollup: MessageFns<MsgStopRollup> = {
  encode(message: MsgStopRollup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.creator !== "") {
      writer.uint32(10).string(message.creator);
    }
    if (message.rollupId !== "") {
      writer.uint32(18).string(message.rollupId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgStopRollup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgStopRollup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.creator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rollupId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgStopRollup {
    return {
      creator: isSet(object.creator) ? globalThis.String(object.creator) : "",
      rollupId: isSet(object.rollupId)
        ? globalThis.String(object.rollupId)
        : isSet(object.rollup_id)
        ? globalThis.String(object.rollup_id)
        : "",
    };
  },

  toJSON(message: MsgStopRollup): unknown {
    const obj: any = {};
    if (message.creator !== "") {
      obj.creator = message.creator;
    }
    if (message.rollupId !== "") {
      obj.rollupId = message.rollupId;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgStopRollup>): MsgStopRollup {
    return MsgStopRollup.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgStopRollup>): MsgStopRollup {
    const message = createBaseMsgStopRollup();
    message.creator = object.creator ?? "";
    message.rollupId = object.rollupId ?? "";
    return message;
  },
};

function createBaseMsgStopRollupResponse(): MsgStopRollupResponse {
  return {};
}

export const MsgStopRollupResponse: MessageFns<MsgStopRollupResponse> = {
  encode(_: MsgStopRollupResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgStopRollupResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgStopRollupResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgStopRollupResponse {
    return {};
  },

  toJSON(_: MsgStopRollupResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<MsgStopRollupResponse>): MsgStopRollupResponse {
    return MsgStopRollupResponse.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<MsgStopRollupResponse>): MsgStopRollupResponse {
    const message = createBaseMsgStopRollupResponse();
    return message;
  },
};

/** Msg defines the rdk module's transaction service. */
export type MsgDefinition = typeof MsgDefinition;
export const MsgDefinition = {
  name: "Msg",
  fullName: "qorechain.rdk.v1.Msg",
  methods: {
    createRollup: {
      name: "CreateRollup",
      requestType: MsgCreateRollup as typeof MsgCreateRollup,
      requestStream: false,
      responseType: MsgCreateRollupResponse as typeof MsgCreateRollupResponse,
      responseStream: false,
      options: {},
    },
    submitBatch: {
      name: "SubmitBatch",
      requestType: MsgSubmitBatch as typeof MsgSubmitBatch,
      requestStream: false,
      responseType: MsgSubmitBatchResponse as typeof MsgSubmitBatchResponse,
      responseStream: false,
      options: {},
    },
    challengeBatch: {
      name: "ChallengeBatch",
      requestType: MsgChallengeBatch as typeof MsgChallengeBatch,
      requestStream: false,
      responseType: MsgChallengeBatchResponse as typeof MsgChallengeBatchResponse,
      responseStream: false,
      options: {},
    },
    resolveChallenge: {
      name: "ResolveChallenge",
      requestType: MsgResolveChallenge as typeof MsgResolveChallenge,
      requestStream: false,
      responseType: MsgResolveChallengeResponse as typeof MsgResolveChallengeResponse,
      responseStream: false,
      options: {},
    },
    pauseRollup: {
      name: "PauseRollup",
      requestType: MsgPauseRollup as typeof MsgPauseRollup,
      requestStream: false,
      responseType: MsgPauseRollupResponse as typeof MsgPauseRollupResponse,
      responseStream: false,
      options: {},
    },
    resumeRollup: {
      name: "ResumeRollup",
      requestType: MsgResumeRollup as typeof MsgResumeRollup,
      requestStream: false,
      responseType: MsgResumeRollupResponse as typeof MsgResumeRollupResponse,
      responseStream: false,
      options: {},
    },
    stopRollup: {
      name: "StopRollup",
      requestType: MsgStopRollup as typeof MsgStopRollup,
      requestStream: false,
      responseType: MsgStopRollupResponse as typeof MsgStopRollupResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
