// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: qorechain/pqc/v1/hybrid.proto
// Protobuf Java Version: 4.35.1

package qorechain.pqc.v1;

@com.google.protobuf.Generated
public final class Hybrid extends com.google.protobuf.GeneratedFile {
  private Hybrid() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Hybrid");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PQCHybridSignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:qorechain.pqc.v1.PQCHybridSignature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * algorithm_id identifies the PQC signature algorithm (e.g. Dilithium-5 = 1).
     * </pre>
     *
     * <code>uint32 algorithm_id = 1 [json_name = "algorithmId", (.gogoproto.customname) = "AlgorithmID", (.gogoproto.casttype) = "AlgorithmID"];</code>
     * @return The algorithmId.
     */
    int getAlgorithmId();

    /**
     * <pre>
     * pqc_signature is the raw PQC signature (Dilithium-5: 4627 bytes).
     * </pre>
     *
     * <code>bytes pqc_signature = 2 [json_name = "pqcSignature", (.gogoproto.customname) = "PQCSignature"];</code>
     * @return The pqcSignature.
     */
    com.google.protobuf.ByteString getPqcSignature();

    /**
     * <pre>
     * pqc_public_key optionally carries the signer's PQC public key
     * (Dilithium-5: 2592 bytes).
     * </pre>
     *
     * <code>bytes pqc_public_key = 3 [json_name = "pqcPublicKey", (.gogoproto.customname) = "PQCPublicKey"];</code>
     * @return The pqcPublicKey.
     */
    com.google.protobuf.ByteString getPqcPublicKey();
  }
  /**
   * <pre>
   * PQCHybridSignature is a transaction extension option carried in
   * TxBody.extension_options. It pairs a post-quantum (Dilithium-5) signature with
   * the account's classical secp256k1 signature so every transaction can be
   * quantum-safe while remaining compatible with the standard Cosmos SDK auth
   * path. It is registered as a cosmos.tx.v1beta1.TxExtensionOptionI.
   * </pre>
   *
   * Protobuf type {@code qorechain.pqc.v1.PQCHybridSignature}
   */
  public static final class PQCHybridSignature extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:qorechain.pqc.v1.PQCHybridSignature)
      PQCHybridSignatureOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "PQCHybridSignature");
    }
    // Use PQCHybridSignature.newBuilder() to construct.
    private PQCHybridSignature(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PQCHybridSignature() {
      pqcSignature_ = com.google.protobuf.ByteString.EMPTY;
      pqcPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qorechain.pqc.v1.Hybrid.internal_static_qorechain_pqc_v1_PQCHybridSignature_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return qorechain.pqc.v1.Hybrid.internal_static_qorechain_pqc_v1_PQCHybridSignature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qorechain.pqc.v1.Hybrid.internal_static_qorechain_pqc_v1_PQCHybridSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qorechain.pqc.v1.Hybrid.PQCHybridSignature.class, qorechain.pqc.v1.Hybrid.PQCHybridSignature.Builder.class);
    }

    public static final int ALGORITHM_ID_FIELD_NUMBER = 1;
    private int algorithmId_ = 0;
    /**
     * <pre>
     * algorithm_id identifies the PQC signature algorithm (e.g. Dilithium-5 = 1).
     * </pre>
     *
     * <code>uint32 algorithm_id = 1 [json_name = "algorithmId", (.gogoproto.customname) = "AlgorithmID", (.gogoproto.casttype) = "AlgorithmID"];</code>
     * @return The algorithmId.
     */
    @java.lang.Override
    public int getAlgorithmId() {
      return algorithmId_;
    }

    public static final int PQC_SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString pqcSignature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * pqc_signature is the raw PQC signature (Dilithium-5: 4627 bytes).
     * </pre>
     *
     * <code>bytes pqc_signature = 2 [json_name = "pqcSignature", (.gogoproto.customname) = "PQCSignature"];</code>
     * @return The pqcSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPqcSignature() {
      return pqcSignature_;
    }

    public static final int PQC_PUBLIC_KEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString pqcPublicKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * pqc_public_key optionally carries the signer's PQC public key
     * (Dilithium-5: 2592 bytes).
     * </pre>
     *
     * <code>bytes pqc_public_key = 3 [json_name = "pqcPublicKey", (.gogoproto.customname) = "PQCPublicKey"];</code>
     * @return The pqcPublicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPqcPublicKey() {
      return pqcPublicKey_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (algorithmId_ != 0) {
        output.writeUInt32(1, algorithmId_);
      }
      if (!pqcSignature_.isEmpty()) {
        output.writeBytes(2, pqcSignature_);
      }
      if (!pqcPublicKey_.isEmpty()) {
        output.writeBytes(3, pqcPublicKey_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (algorithmId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, algorithmId_);
      }
      if (!pqcSignature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, pqcSignature_);
      }
      if (!pqcPublicKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, pqcPublicKey_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof qorechain.pqc.v1.Hybrid.PQCHybridSignature)) {
        return super.equals(obj);
      }
      qorechain.pqc.v1.Hybrid.PQCHybridSignature other = (qorechain.pqc.v1.Hybrid.PQCHybridSignature) obj;

      if (getAlgorithmId()
          != other.getAlgorithmId()) return false;
      if (!getPqcSignature()
          .equals(other.getPqcSignature())) return false;
      if (!getPqcPublicKey()
          .equals(other.getPqcPublicKey())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALGORITHM_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAlgorithmId();
      hash = (37 * hash) + PQC_SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getPqcSignature().hashCode();
      hash = (37 * hash) + PQC_PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPqcPublicKey().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(qorechain.pqc.v1.Hybrid.PQCHybridSignature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PQCHybridSignature is a transaction extension option carried in
     * TxBody.extension_options. It pairs a post-quantum (Dilithium-5) signature with
     * the account's classical secp256k1 signature so every transaction can be
     * quantum-safe while remaining compatible with the standard Cosmos SDK auth
     * path. It is registered as a cosmos.tx.v1beta1.TxExtensionOptionI.
     * </pre>
     *
     * Protobuf type {@code qorechain.pqc.v1.PQCHybridSignature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:qorechain.pqc.v1.PQCHybridSignature)
        qorechain.pqc.v1.Hybrid.PQCHybridSignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qorechain.pqc.v1.Hybrid.internal_static_qorechain_pqc_v1_PQCHybridSignature_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qorechain.pqc.v1.Hybrid.internal_static_qorechain_pqc_v1_PQCHybridSignature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qorechain.pqc.v1.Hybrid.PQCHybridSignature.class, qorechain.pqc.v1.Hybrid.PQCHybridSignature.Builder.class);
      }

      // Construct using qorechain.pqc.v1.Hybrid.PQCHybridSignature.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        algorithmId_ = 0;
        pqcSignature_ = com.google.protobuf.ByteString.EMPTY;
        pqcPublicKey_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qorechain.pqc.v1.Hybrid.internal_static_qorechain_pqc_v1_PQCHybridSignature_descriptor;
      }

      @java.lang.Override
      public qorechain.pqc.v1.Hybrid.PQCHybridSignature getDefaultInstanceForType() {
        return qorechain.pqc.v1.Hybrid.PQCHybridSignature.getDefaultInstance();
      }

      @java.lang.Override
      public qorechain.pqc.v1.Hybrid.PQCHybridSignature build() {
        qorechain.pqc.v1.Hybrid.PQCHybridSignature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public qorechain.pqc.v1.Hybrid.PQCHybridSignature buildPartial() {
        qorechain.pqc.v1.Hybrid.PQCHybridSignature result = new qorechain.pqc.v1.Hybrid.PQCHybridSignature(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(qorechain.pqc.v1.Hybrid.PQCHybridSignature result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.algorithmId_ = algorithmId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pqcSignature_ = pqcSignature_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.pqcPublicKey_ = pqcPublicKey_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qorechain.pqc.v1.Hybrid.PQCHybridSignature) {
          return mergeFrom((qorechain.pqc.v1.Hybrid.PQCHybridSignature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qorechain.pqc.v1.Hybrid.PQCHybridSignature other) {
        if (other == qorechain.pqc.v1.Hybrid.PQCHybridSignature.getDefaultInstance()) return this;
        if (other.getAlgorithmId() != 0) {
          setAlgorithmId(other.getAlgorithmId());
        }
        if (!other.getPqcSignature().isEmpty()) {
          setPqcSignature(other.getPqcSignature());
        }
        if (!other.getPqcPublicKey().isEmpty()) {
          setPqcPublicKey(other.getPqcPublicKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                algorithmId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                pqcSignature_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                pqcPublicKey_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int algorithmId_ ;
      /**
       * <pre>
       * algorithm_id identifies the PQC signature algorithm (e.g. Dilithium-5 = 1).
       * </pre>
       *
       * <code>uint32 algorithm_id = 1 [json_name = "algorithmId", (.gogoproto.customname) = "AlgorithmID", (.gogoproto.casttype) = "AlgorithmID"];</code>
       * @return The algorithmId.
       */
      @java.lang.Override
      public int getAlgorithmId() {
        return algorithmId_;
      }
      /**
       * <pre>
       * algorithm_id identifies the PQC signature algorithm (e.g. Dilithium-5 = 1).
       * </pre>
       *
       * <code>uint32 algorithm_id = 1 [json_name = "algorithmId", (.gogoproto.customname) = "AlgorithmID", (.gogoproto.casttype) = "AlgorithmID"];</code>
       * @param value The algorithmId to set.
       * @return This builder for chaining.
       */
      public Builder setAlgorithmId(int value) {

        algorithmId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * algorithm_id identifies the PQC signature algorithm (e.g. Dilithium-5 = 1).
       * </pre>
       *
       * <code>uint32 algorithm_id = 1 [json_name = "algorithmId", (.gogoproto.customname) = "AlgorithmID", (.gogoproto.casttype) = "AlgorithmID"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAlgorithmId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        algorithmId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pqcSignature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * pqc_signature is the raw PQC signature (Dilithium-5: 4627 bytes).
       * </pre>
       *
       * <code>bytes pqc_signature = 2 [json_name = "pqcSignature", (.gogoproto.customname) = "PQCSignature"];</code>
       * @return The pqcSignature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPqcSignature() {
        return pqcSignature_;
      }
      /**
       * <pre>
       * pqc_signature is the raw PQC signature (Dilithium-5: 4627 bytes).
       * </pre>
       *
       * <code>bytes pqc_signature = 2 [json_name = "pqcSignature", (.gogoproto.customname) = "PQCSignature"];</code>
       * @param value The pqcSignature to set.
       * @return This builder for chaining.
       */
      public Builder setPqcSignature(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        pqcSignature_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * pqc_signature is the raw PQC signature (Dilithium-5: 4627 bytes).
       * </pre>
       *
       * <code>bytes pqc_signature = 2 [json_name = "pqcSignature", (.gogoproto.customname) = "PQCSignature"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPqcSignature() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pqcSignature_ = getDefaultInstance().getPqcSignature();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pqcPublicKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * pqc_public_key optionally carries the signer's PQC public key
       * (Dilithium-5: 2592 bytes).
       * </pre>
       *
       * <code>bytes pqc_public_key = 3 [json_name = "pqcPublicKey", (.gogoproto.customname) = "PQCPublicKey"];</code>
       * @return The pqcPublicKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPqcPublicKey() {
        return pqcPublicKey_;
      }
      /**
       * <pre>
       * pqc_public_key optionally carries the signer's PQC public key
       * (Dilithium-5: 2592 bytes).
       * </pre>
       *
       * <code>bytes pqc_public_key = 3 [json_name = "pqcPublicKey", (.gogoproto.customname) = "PQCPublicKey"];</code>
       * @param value The pqcPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPqcPublicKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        pqcPublicKey_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * pqc_public_key optionally carries the signer's PQC public key
       * (Dilithium-5: 2592 bytes).
       * </pre>
       *
       * <code>bytes pqc_public_key = 3 [json_name = "pqcPublicKey", (.gogoproto.customname) = "PQCPublicKey"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPqcPublicKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pqcPublicKey_ = getDefaultInstance().getPqcPublicKey();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:qorechain.pqc.v1.PQCHybridSignature)
    }

    // @@protoc_insertion_point(class_scope:qorechain.pqc.v1.PQCHybridSignature)
    private static final qorechain.pqc.v1.Hybrid.PQCHybridSignature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new qorechain.pqc.v1.Hybrid.PQCHybridSignature();
    }

    public static qorechain.pqc.v1.Hybrid.PQCHybridSignature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PQCHybridSignature>
        PARSER = new com.google.protobuf.AbstractParser<PQCHybridSignature>() {
      @java.lang.Override
      public PQCHybridSignature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PQCHybridSignature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PQCHybridSignature> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public qorechain.pqc.v1.Hybrid.PQCHybridSignature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qorechain_pqc_v1_PQCHybridSignature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_qorechain_pqc_v1_PQCHybridSignature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035qorechain/pqc/v1/hybrid.proto\022\020qorecha" +
      "in.pqc.v1\032\024gogoproto/gogo.proto\"\306\001\n\022PQCH" +
      "ybridSignature\022A\n\014algorithm_id\030\001 \001(\rB\036\342\336" +
      "\037\013AlgorithmID\372\336\037\013AlgorithmIDR\013algorithmI" +
      "d\0225\n\rpqc_signature\030\002 \001(\014B\020\342\336\037\014PQCSignatu" +
      "reR\014pqcSignature\0226\n\016pqc_public_key\030\003 \001(\014" +
      "B\020\342\336\037\014PQCPublicKeyR\014pqcPublicKeyB1Z/gith" +
      "ub.com/qorechain/qorechain-core/x/pqc/ty" +
      "pesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
        });
    internal_static_qorechain_pqc_v1_PQCHybridSignature_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_qorechain_pqc_v1_PQCHybridSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_qorechain_pqc_v1_PQCHybridSignature_descriptor,
        new java.lang.String[] { "AlgorithmId", "PqcSignature", "PqcPublicKey", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.GoGoProtos.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.casttype);
    registry.add(com.google.protobuf.GoGoProtos.customname);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
