// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/reputation/v1/query.proto

package reputationv1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffe4f5d705afffd, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Alpha    string `protobuf:"bytes,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta     string `protobuf:"bytes,2,opt,name=beta,proto3" json:"beta,omitempty"`
	Gamma    string `protobuf:"bytes,3,opt,name=gamma,proto3" json:"gamma,omitempty"`
	Delta    string `protobuf:"bytes,4,opt,name=delta,proto3" json:"delta,omitempty"`
	Lambda   string `protobuf:"bytes,5,opt,name=lambda,proto3" json:"lambda,omitempty"`
	MinScore string `protobuf:"bytes,6,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ffe4f5d705afffd, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetAlpha() string {
	if m != nil {
		return m.Alpha
	}
	return ""
}

func (m *QueryParamsResponse) GetBeta() string {
	if m != nil {
		return m.Beta
	}
	return ""
}

func (m *QueryParamsResponse) GetGamma() string {
	if m != nil {
		return m.Gamma
	}
	return ""
}

func (m *QueryParamsResponse) GetDelta() string {
	if m != nil {
		return m.Delta
	}
	return ""
}

func (m *QueryParamsResponse) GetLambda() string {
	if m != nil {
		return m.Lambda
	}
	return ""
}

func (m *QueryParamsResponse) GetMinScore() string {
	if m != nil {
		return m.MinScore
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "qorechain.reputation.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "qorechain.reputation.v1.QueryParamsResponse")
}

func init() {
	proto.RegisterFile("qorechain/reputation/v1/query.proto", fileDescriptor_4ffe4f5d705afffd)
}

var fileDescriptor_4ffe4f5d705afffd = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xeb, 0x40,
	0x18, 0x85, 0x9b, 0xb4, 0x0d, 0xb7, 0xb3, 0x9c, 0x5b, 0x6e, 0x73, 0x6f, 0x21, 0x5c, 0xda, 0x8d,
	0xa0, 0x26, 0x44, 0x77, 0x71, 0xd7, 0x8d, 0x2b, 0xa1, 0x8d, 0x50, 0x44, 0x0a, 0xf2, 0x27, 0x19,
	0xd2, 0xd0, 0x4c, 0x26, 0x4d, 0x26, 0x05, 0xdf, 0xc2, 0x47, 0x10, 0x71, 0xe5, 0x93, 0x88, 0xab,
	0x2e, 0x5d, 0x4a, 0xba, 0xf3, 0x29, 0x24, 0x13, 0x49, 0x2a, 0x12, 0x70, 0x37, 0xe7, 0x9c, 0x8f,
	0xe1, 0xfc, 0x1c, 0x34, 0x5e, 0xb3, 0x84, 0xb8, 0x4b, 0x08, 0x22, 0x23, 0x21, 0x71, 0xc6, 0x81,
	0x07, 0x2c, 0x32, 0x36, 0xa6, 0xb1, 0xce, 0x48, 0x72, 0xab, 0xc7, 0x09, 0xe3, 0x0c, 0x0f, 0x2a,
	0x48, 0xaf, 0x21, 0x7d, 0x63, 0x8e, 0xfa, 0x08, 0xcf, 0x0a, 0x6e, 0x0a, 0x09, 0xd0, 0xd4, 0x26,
	0xeb, 0x8c, 0xa4, 0x7c, 0x74, 0x2f, 0xa1, 0xdf, 0x5f, 0xec, 0x34, 0x66, 0x51, 0x4a, 0x70, 0x1f,
	0x75, 0x21, 0x8c, 0x97, 0xa0, 0x4a, 0xff, 0xa5, 0x83, 0x9e, 0x5d, 0x0a, 0x8c, 0x51, 0xc7, 0x21,
	0x1c, 0x54, 0x59, 0x98, 0xe2, 0x5d, 0x90, 0x3e, 0x50, 0x0a, 0x6a, 0xbb, 0x24, 0x85, 0x28, 0x5c,
	0x8f, 0x84, 0x1c, 0xd4, 0x4e, 0xe9, 0x0a, 0x81, 0xff, 0x20, 0x25, 0x04, 0xea, 0x78, 0xa0, 0x76,
	0x85, 0xfd, 0xa9, 0xf0, 0x10, 0xf5, 0x68, 0x10, 0xdd, 0xa4, 0x2e, 0x4b, 0x88, 0xaa, 0x88, 0xe8,
	0x17, 0x0d, 0xa2, 0xcb, 0x42, 0x9f, 0x84, 0xa8, 0x2b, 0x1a, 0x62, 0x17, 0x29, 0x65, 0x4b, 0x7c,
	0xa8, 0x37, 0x5c, 0xa9, 0x7f, 0x3f, 0xf1, 0xdf, 0xd1, 0xcf, 0xe0, 0xf2, 0xf0, 0xc9, 0xa3, 0xfc,
	0x9c, 0x6b, 0xd2, 0x36, 0xd7, 0xa4, 0xb7, 0x5c, 0x93, 0xee, 0x76, 0x5a, 0x6b, 0xbb, 0xd3, 0x5a,
	0xaf, 0x3b, 0xad, 0x85, 0x86, 0x2e, 0xa3, 0x4d, 0x7f, 0x4d, 0x50, 0xf9, 0x59, 0xb1, 0xc1, 0x54,
	0xba, 0x76, 0xfd, 0x80, 0x2f, 0x33, 0x47, 0x77, 0x19, 0x35, 0xea, 0xd5, 0xaa, 0xd7, 0x71, 0xea,
	0xad, 0x8c, 0x18, 0xdc, 0x15, 0xf8, 0x24, 0x35, 0x7c, 0xb6, 0xc7, 0x88, 0x15, 0x8d, 0x86, 0xa5,
	0xcf, 0x6a, 0xb5, 0x31, 0x1f, 0xe4, 0xf6, 0xcc, 0xbe, 0x7a, 0x92, 0x07, 0xb3, 0xaa, 0x92, 0x5d,
	0x57, 0x9a, 0x9b, 0x2f, 0x7b, 0xc9, 0xa2, 0x4e, 0x16, 0x73, 0x33, 0x97, 0xc7, 0x0d, 0xc9, 0xe2,
	0x7c, 0x3a, 0xb9, 0x20, 0x1c, 0x3c, 0xe0, 0xf0, 0x2e, 0xff, 0xad, 0x28, 0xcb, 0xaa, 0x31, 0xcb,
	0x9a, 0x9b, 0x8e, 0x22, 0x7a, 0x9e, 0x7e, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x3a, 0x69, 0x83,
	0x94, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the reputation formula weights (R_i = α·S_i + β·P_i + γ·C_i + δ·T_i).
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/qorechain.reputation.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the reputation formula weights (R_i = α·S_i + β·P_i + γ·C_i + δ·T_i).
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.reputation.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.reputation.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/reputation/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MinScore) > 0 {
		i -= len(m.MinScore)
		copy(dAtA[i:], m.MinScore)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MinScore)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Lambda) > 0 {
		i -= len(m.Lambda)
		copy(dAtA[i:], m.Lambda)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Lambda)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Delta) > 0 {
		i -= len(m.Delta)
		copy(dAtA[i:], m.Delta)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Delta)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Gamma) > 0 {
		i -= len(m.Gamma)
		copy(dAtA[i:], m.Gamma)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Gamma)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Beta) > 0 {
		i -= len(m.Beta)
		copy(dAtA[i:], m.Beta)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Beta)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Alpha) > 0 {
		i -= len(m.Alpha)
		copy(dAtA[i:], m.Alpha)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Alpha)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Alpha)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Beta)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Gamma)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Delta)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Lambda)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.MinScore)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alpha", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Alpha = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Beta = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gamma", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Gamma = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delta = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lambda", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lambda = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinScore", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinScore = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
