// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: qorechain/qca/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "qorechain.qca.v1";

export interface QueryConfigRequest {
}

export interface QueryConfigResponse {
  useReputationWeighting: boolean;
  minReputationScore: number;
  /** PoolConfig */
  poolClassificationInterval: string;
  poolWeightRpos: string;
  poolWeightDpos: string;
  poolMinDelegationDpos: string;
  poolRepPercentileRpos: string;
  /** BondingCurveConfig */
  bondingAlpha: string;
  bondingBeta: string;
  bondingPhaseMultiplier: string;
  /** SlashingConfig */
  slashingBaseRate: string;
  slashingEscalationFactor: string;
  slashingMaxPenalty: string;
  slashingDecayHalflife: string;
  /** QDRWConfig */
  qdrwEnabled: boolean;
  qdrwXqoreMultiplier: string;
  qdrwRepMinMultiplier: string;
  qdrwRepMaxMultiplier: string;
}

function createBaseQueryConfigRequest(): QueryConfigRequest {
  return {};
}

export const QueryConfigRequest: MessageFns<QueryConfigRequest> = {
  encode(_: QueryConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryConfigRequest {
    return {};
  },

  toJSON(_: QueryConfigRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<QueryConfigRequest>): QueryConfigRequest {
    return QueryConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<QueryConfigRequest>): QueryConfigRequest {
    const message = createBaseQueryConfigRequest();
    return message;
  },
};

function createBaseQueryConfigResponse(): QueryConfigResponse {
  return {
    useReputationWeighting: false,
    minReputationScore: 0,
    poolClassificationInterval: "0",
    poolWeightRpos: "",
    poolWeightDpos: "",
    poolMinDelegationDpos: "0",
    poolRepPercentileRpos: "0",
    bondingAlpha: "",
    bondingBeta: "",
    bondingPhaseMultiplier: "",
    slashingBaseRate: "",
    slashingEscalationFactor: "",
    slashingMaxPenalty: "",
    slashingDecayHalflife: "0",
    qdrwEnabled: false,
    qdrwXqoreMultiplier: "",
    qdrwRepMinMultiplier: "",
    qdrwRepMaxMultiplier: "",
  };
}

export const QueryConfigResponse: MessageFns<QueryConfigResponse> = {
  encode(message: QueryConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.useReputationWeighting !== false) {
      writer.uint32(8).bool(message.useReputationWeighting);
    }
    if (message.minReputationScore !== 0) {
      writer.uint32(17).double(message.minReputationScore);
    }
    if (message.poolClassificationInterval !== "0") {
      writer.uint32(24).uint64(message.poolClassificationInterval);
    }
    if (message.poolWeightRpos !== "") {
      writer.uint32(34).string(message.poolWeightRpos);
    }
    if (message.poolWeightDpos !== "") {
      writer.uint32(42).string(message.poolWeightDpos);
    }
    if (message.poolMinDelegationDpos !== "0") {
      writer.uint32(48).uint64(message.poolMinDelegationDpos);
    }
    if (message.poolRepPercentileRpos !== "0") {
      writer.uint32(56).uint64(message.poolRepPercentileRpos);
    }
    if (message.bondingAlpha !== "") {
      writer.uint32(66).string(message.bondingAlpha);
    }
    if (message.bondingBeta !== "") {
      writer.uint32(74).string(message.bondingBeta);
    }
    if (message.bondingPhaseMultiplier !== "") {
      writer.uint32(82).string(message.bondingPhaseMultiplier);
    }
    if (message.slashingBaseRate !== "") {
      writer.uint32(90).string(message.slashingBaseRate);
    }
    if (message.slashingEscalationFactor !== "") {
      writer.uint32(98).string(message.slashingEscalationFactor);
    }
    if (message.slashingMaxPenalty !== "") {
      writer.uint32(106).string(message.slashingMaxPenalty);
    }
    if (message.slashingDecayHalflife !== "0") {
      writer.uint32(112).uint64(message.slashingDecayHalflife);
    }
    if (message.qdrwEnabled !== false) {
      writer.uint32(120).bool(message.qdrwEnabled);
    }
    if (message.qdrwXqoreMultiplier !== "") {
      writer.uint32(130).string(message.qdrwXqoreMultiplier);
    }
    if (message.qdrwRepMinMultiplier !== "") {
      writer.uint32(138).string(message.qdrwRepMinMultiplier);
    }
    if (message.qdrwRepMaxMultiplier !== "") {
      writer.uint32(146).string(message.qdrwRepMaxMultiplier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.useReputationWeighting = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.minReputationScore = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.poolClassificationInterval = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.poolWeightRpos = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.poolWeightDpos = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.poolMinDelegationDpos = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.poolRepPercentileRpos = reader.uint64().toString();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.bondingAlpha = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.bondingBeta = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.bondingPhaseMultiplier = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.slashingBaseRate = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.slashingEscalationFactor = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.slashingMaxPenalty = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.slashingDecayHalflife = reader.uint64().toString();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.qdrwEnabled = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.qdrwXqoreMultiplier = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.qdrwRepMinMultiplier = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.qdrwRepMaxMultiplier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryConfigResponse {
    return {
      useReputationWeighting: isSet(object.useReputationWeighting)
        ? globalThis.Boolean(object.useReputationWeighting)
        : isSet(object.use_reputation_weighting)
        ? globalThis.Boolean(object.use_reputation_weighting)
        : false,
      minReputationScore: isSet(object.minReputationScore)
        ? globalThis.Number(object.minReputationScore)
        : isSet(object.min_reputation_score)
        ? globalThis.Number(object.min_reputation_score)
        : 0,
      poolClassificationInterval: isSet(object.poolClassificationInterval)
        ? globalThis.String(object.poolClassificationInterval)
        : isSet(object.pool_classification_interval)
        ? globalThis.String(object.pool_classification_interval)
        : "0",
      poolWeightRpos: isSet(object.poolWeightRpos)
        ? globalThis.String(object.poolWeightRpos)
        : isSet(object.pool_weight_rpos)
        ? globalThis.String(object.pool_weight_rpos)
        : "",
      poolWeightDpos: isSet(object.poolWeightDpos)
        ? globalThis.String(object.poolWeightDpos)
        : isSet(object.pool_weight_dpos)
        ? globalThis.String(object.pool_weight_dpos)
        : "",
      poolMinDelegationDpos: isSet(object.poolMinDelegationDpos)
        ? globalThis.String(object.poolMinDelegationDpos)
        : isSet(object.pool_min_delegation_dpos)
        ? globalThis.String(object.pool_min_delegation_dpos)
        : "0",
      poolRepPercentileRpos: isSet(object.poolRepPercentileRpos)
        ? globalThis.String(object.poolRepPercentileRpos)
        : isSet(object.pool_rep_percentile_rpos)
        ? globalThis.String(object.pool_rep_percentile_rpos)
        : "0",
      bondingAlpha: isSet(object.bondingAlpha)
        ? globalThis.String(object.bondingAlpha)
        : isSet(object.bonding_alpha)
        ? globalThis.String(object.bonding_alpha)
        : "",
      bondingBeta: isSet(object.bondingBeta)
        ? globalThis.String(object.bondingBeta)
        : isSet(object.bonding_beta)
        ? globalThis.String(object.bonding_beta)
        : "",
      bondingPhaseMultiplier: isSet(object.bondingPhaseMultiplier)
        ? globalThis.String(object.bondingPhaseMultiplier)
        : isSet(object.bonding_phase_multiplier)
        ? globalThis.String(object.bonding_phase_multiplier)
        : "",
      slashingBaseRate: isSet(object.slashingBaseRate)
        ? globalThis.String(object.slashingBaseRate)
        : isSet(object.slashing_base_rate)
        ? globalThis.String(object.slashing_base_rate)
        : "",
      slashingEscalationFactor: isSet(object.slashingEscalationFactor)
        ? globalThis.String(object.slashingEscalationFactor)
        : isSet(object.slashing_escalation_factor)
        ? globalThis.String(object.slashing_escalation_factor)
        : "",
      slashingMaxPenalty: isSet(object.slashingMaxPenalty)
        ? globalThis.String(object.slashingMaxPenalty)
        : isSet(object.slashing_max_penalty)
        ? globalThis.String(object.slashing_max_penalty)
        : "",
      slashingDecayHalflife: isSet(object.slashingDecayHalflife)
        ? globalThis.String(object.slashingDecayHalflife)
        : isSet(object.slashing_decay_halflife)
        ? globalThis.String(object.slashing_decay_halflife)
        : "0",
      qdrwEnabled: isSet(object.qdrwEnabled)
        ? globalThis.Boolean(object.qdrwEnabled)
        : isSet(object.qdrw_enabled)
        ? globalThis.Boolean(object.qdrw_enabled)
        : false,
      qdrwXqoreMultiplier: isSet(object.qdrwXqoreMultiplier)
        ? globalThis.String(object.qdrwXqoreMultiplier)
        : isSet(object.qdrw_xqore_multiplier)
        ? globalThis.String(object.qdrw_xqore_multiplier)
        : "",
      qdrwRepMinMultiplier: isSet(object.qdrwRepMinMultiplier)
        ? globalThis.String(object.qdrwRepMinMultiplier)
        : isSet(object.qdrw_rep_min_multiplier)
        ? globalThis.String(object.qdrw_rep_min_multiplier)
        : "",
      qdrwRepMaxMultiplier: isSet(object.qdrwRepMaxMultiplier)
        ? globalThis.String(object.qdrwRepMaxMultiplier)
        : isSet(object.qdrw_rep_max_multiplier)
        ? globalThis.String(object.qdrw_rep_max_multiplier)
        : "",
    };
  },

  toJSON(message: QueryConfigResponse): unknown {
    const obj: any = {};
    if (message.useReputationWeighting !== false) {
      obj.useReputationWeighting = message.useReputationWeighting;
    }
    if (message.minReputationScore !== 0) {
      obj.minReputationScore = message.minReputationScore;
    }
    if (message.poolClassificationInterval !== "0") {
      obj.poolClassificationInterval = message.poolClassificationInterval;
    }
    if (message.poolWeightRpos !== "") {
      obj.poolWeightRpos = message.poolWeightRpos;
    }
    if (message.poolWeightDpos !== "") {
      obj.poolWeightDpos = message.poolWeightDpos;
    }
    if (message.poolMinDelegationDpos !== "0") {
      obj.poolMinDelegationDpos = message.poolMinDelegationDpos;
    }
    if (message.poolRepPercentileRpos !== "0") {
      obj.poolRepPercentileRpos = message.poolRepPercentileRpos;
    }
    if (message.bondingAlpha !== "") {
      obj.bondingAlpha = message.bondingAlpha;
    }
    if (message.bondingBeta !== "") {
      obj.bondingBeta = message.bondingBeta;
    }
    if (message.bondingPhaseMultiplier !== "") {
      obj.bondingPhaseMultiplier = message.bondingPhaseMultiplier;
    }
    if (message.slashingBaseRate !== "") {
      obj.slashingBaseRate = message.slashingBaseRate;
    }
    if (message.slashingEscalationFactor !== "") {
      obj.slashingEscalationFactor = message.slashingEscalationFactor;
    }
    if (message.slashingMaxPenalty !== "") {
      obj.slashingMaxPenalty = message.slashingMaxPenalty;
    }
    if (message.slashingDecayHalflife !== "0") {
      obj.slashingDecayHalflife = message.slashingDecayHalflife;
    }
    if (message.qdrwEnabled !== false) {
      obj.qdrwEnabled = message.qdrwEnabled;
    }
    if (message.qdrwXqoreMultiplier !== "") {
      obj.qdrwXqoreMultiplier = message.qdrwXqoreMultiplier;
    }
    if (message.qdrwRepMinMultiplier !== "") {
      obj.qdrwRepMinMultiplier = message.qdrwRepMinMultiplier;
    }
    if (message.qdrwRepMaxMultiplier !== "") {
      obj.qdrwRepMaxMultiplier = message.qdrwRepMaxMultiplier;
    }
    return obj;
  },

  create(base?: DeepPartial<QueryConfigResponse>): QueryConfigResponse {
    return QueryConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryConfigResponse>): QueryConfigResponse {
    const message = createBaseQueryConfigResponse();
    message.useReputationWeighting = object.useReputationWeighting ?? false;
    message.minReputationScore = object.minReputationScore ?? 0;
    message.poolClassificationInterval = object.poolClassificationInterval ?? "0";
    message.poolWeightRpos = object.poolWeightRpos ?? "";
    message.poolWeightDpos = object.poolWeightDpos ?? "";
    message.poolMinDelegationDpos = object.poolMinDelegationDpos ?? "0";
    message.poolRepPercentileRpos = object.poolRepPercentileRpos ?? "0";
    message.bondingAlpha = object.bondingAlpha ?? "";
    message.bondingBeta = object.bondingBeta ?? "";
    message.bondingPhaseMultiplier = object.bondingPhaseMultiplier ?? "";
    message.slashingBaseRate = object.slashingBaseRate ?? "";
    message.slashingEscalationFactor = object.slashingEscalationFactor ?? "";
    message.slashingMaxPenalty = object.slashingMaxPenalty ?? "";
    message.slashingDecayHalflife = object.slashingDecayHalflife ?? "0";
    message.qdrwEnabled = object.qdrwEnabled ?? false;
    message.qdrwXqoreMultiplier = object.qdrwXqoreMultiplier ?? "";
    message.qdrwRepMinMultiplier = object.qdrwRepMinMultiplier ?? "";
    message.qdrwRepMaxMultiplier = object.qdrwRepMaxMultiplier ?? "";
    return message;
  },
};

/** Query defines the qca module's gRPC query service. */
export type QueryDefinition = typeof QueryDefinition;
export const QueryDefinition = {
  name: "Query",
  fullName: "qorechain.qca.v1.Query",
  methods: {
    /**
     * Config returns the live QCA consensus configuration (pool, bonding curve,
     * slashing and QDRW sub-configs flattened).
     */
    config: {
      name: "Config",
      requestType: QueryConfigRequest as typeof QueryConfigRequest,
      requestStream: false,
      responseType: QueryConfigResponse as typeof QueryConfigResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
