// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    #[prost(string, tag="1")]
    pub alpha: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub beta: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub gamma: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub delta: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub lambda: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub min_score: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
