// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: qorechain/bridge/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "qorechain.bridge.v1";

export interface BridgeConfigView {
  minValidators: number;
  attestationThreshold: number;
  challengePeriodSecs: string;
  largeTransferThreshold: string;
  enabled: boolean;
}

export interface ChainConfigView {
  chainId: string;
  name: string;
  chainType: string;
  bridgeContract: string;
  status: string;
  minConfirmations: number;
  architecture: string;
  ibcChannelId: string;
  ibcPortId: string;
}

export interface BridgeValidatorView {
  address: string;
  supportedChains: string[];
  reputation: string;
  active: boolean;
  registeredAt: string;
}

export interface BridgeOperationView {
  id: string;
  type: string;
  sourceChain: string;
  destChain: string;
  sender: string;
  receiver: string;
  asset: string;
  amount: string;
  sourceTxHash: string;
  status: string;
}

export interface QueryConfigRequest {
}

export interface QueryConfigResponse {
  config?: BridgeConfigView | undefined;
}

export interface QueryChainConfigRequest {
  chainId: string;
}

export interface QueryChainConfigResponse {
  chain?: ChainConfigView | undefined;
}

export interface QueryChainConfigsRequest {
}

export interface QueryChainConfigsResponse {
  chains: ChainConfigView[];
}

export interface QueryValidatorRequest {
  address: string;
}

export interface QueryValidatorResponse {
  validator?: BridgeValidatorView | undefined;
}

export interface QueryValidatorsRequest {
}

export interface QueryValidatorsResponse {
  validators: BridgeValidatorView[];
}

export interface QueryOperationRequest {
  id: string;
}

export interface QueryOperationResponse {
  operation?: BridgeOperationView | undefined;
}

export interface QueryOperationsRequest {
}

export interface QueryOperationsResponse {
  operations: BridgeOperationView[];
}

function createBaseBridgeConfigView(): BridgeConfigView {
  return {
    minValidators: 0,
    attestationThreshold: 0,
    challengePeriodSecs: "0",
    largeTransferThreshold: "",
    enabled: false,
  };
}

export const BridgeConfigView: MessageFns<BridgeConfigView> = {
  encode(message: BridgeConfigView, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.minValidators !== 0) {
      writer.uint32(8).int32(message.minValidators);
    }
    if (message.attestationThreshold !== 0) {
      writer.uint32(16).int32(message.attestationThreshold);
    }
    if (message.challengePeriodSecs !== "0") {
      writer.uint32(24).int64(message.challengePeriodSecs);
    }
    if (message.largeTransferThreshold !== "") {
      writer.uint32(34).string(message.largeTransferThreshold);
    }
    if (message.enabled !== false) {
      writer.uint32(40).bool(message.enabled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BridgeConfigView {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBridgeConfigView();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.minValidators = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.attestationThreshold = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.challengePeriodSecs = reader.int64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.largeTransferThreshold = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.enabled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BridgeConfigView {
    return {
      minValidators: isSet(object.minValidators)
        ? globalThis.Number(object.minValidators)
        : isSet(object.min_validators)
        ? globalThis.Number(object.min_validators)
        : 0,
      attestationThreshold: isSet(object.attestationThreshold)
        ? globalThis.Number(object.attestationThreshold)
        : isSet(object.attestation_threshold)
        ? globalThis.Number(object.attestation_threshold)
        : 0,
      challengePeriodSecs: isSet(object.challengePeriodSecs)
        ? globalThis.String(object.challengePeriodSecs)
        : isSet(object.challenge_period_secs)
        ? globalThis.String(object.challenge_period_secs)
        : "0",
      largeTransferThreshold: isSet(object.largeTransferThreshold)
        ? globalThis.String(object.largeTransferThreshold)
        : isSet(object.large_transfer_threshold)
        ? globalThis.String(object.large_transfer_threshold)
        : "",
      enabled: isSet(object.enabled) ? globalThis.Boolean(object.enabled) : false,
    };
  },

  toJSON(message: BridgeConfigView): unknown {
    const obj: any = {};
    if (message.minValidators !== 0) {
      obj.minValidators = Math.round(message.minValidators);
    }
    if (message.attestationThreshold !== 0) {
      obj.attestationThreshold = Math.round(message.attestationThreshold);
    }
    if (message.challengePeriodSecs !== "0") {
      obj.challengePeriodSecs = message.challengePeriodSecs;
    }
    if (message.largeTransferThreshold !== "") {
      obj.largeTransferThreshold = message.largeTransferThreshold;
    }
    if (message.enabled !== false) {
      obj.enabled = message.enabled;
    }
    return obj;
  },

  create(base?: DeepPartial<BridgeConfigView>): BridgeConfigView {
    return BridgeConfigView.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BridgeConfigView>): BridgeConfigView {
    const message = createBaseBridgeConfigView();
    message.minValidators = object.minValidators ?? 0;
    message.attestationThreshold = object.attestationThreshold ?? 0;
    message.challengePeriodSecs = object.challengePeriodSecs ?? "0";
    message.largeTransferThreshold = object.largeTransferThreshold ?? "";
    message.enabled = object.enabled ?? false;
    return message;
  },
};

function createBaseChainConfigView(): ChainConfigView {
  return {
    chainId: "",
    name: "",
    chainType: "",
    bridgeContract: "",
    status: "",
    minConfirmations: 0,
    architecture: "",
    ibcChannelId: "",
    ibcPortId: "",
  };
}

export const ChainConfigView: MessageFns<ChainConfigView> = {
  encode(message: ChainConfigView, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.chainType !== "") {
      writer.uint32(26).string(message.chainType);
    }
    if (message.bridgeContract !== "") {
      writer.uint32(34).string(message.bridgeContract);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.minConfirmations !== 0) {
      writer.uint32(48).int32(message.minConfirmations);
    }
    if (message.architecture !== "") {
      writer.uint32(58).string(message.architecture);
    }
    if (message.ibcChannelId !== "") {
      writer.uint32(66).string(message.ibcChannelId);
    }
    if (message.ibcPortId !== "") {
      writer.uint32(74).string(message.ibcPortId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChainConfigView {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChainConfigView();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chainId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.chainType = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.bridgeContract = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.minConfirmations = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.architecture = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.ibcChannelId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.ibcPortId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChainConfigView {
    return {
      chainId: isSet(object.chainId)
        ? globalThis.String(object.chainId)
        : isSet(object.chain_id)
        ? globalThis.String(object.chain_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      chainType: isSet(object.chainType)
        ? globalThis.String(object.chainType)
        : isSet(object.chain_type)
        ? globalThis.String(object.chain_type)
        : "",
      bridgeContract: isSet(object.bridgeContract)
        ? globalThis.String(object.bridgeContract)
        : isSet(object.bridge_contract)
        ? globalThis.String(object.bridge_contract)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      minConfirmations: isSet(object.minConfirmations)
        ? globalThis.Number(object.minConfirmations)
        : isSet(object.min_confirmations)
        ? globalThis.Number(object.min_confirmations)
        : 0,
      architecture: isSet(object.architecture) ? globalThis.String(object.architecture) : "",
      ibcChannelId: isSet(object.ibcChannelId)
        ? globalThis.String(object.ibcChannelId)
        : isSet(object.ibc_channel_id)
        ? globalThis.String(object.ibc_channel_id)
        : "",
      ibcPortId: isSet(object.ibcPortId)
        ? globalThis.String(object.ibcPortId)
        : isSet(object.ibc_port_id)
        ? globalThis.String(object.ibc_port_id)
        : "",
    };
  },

  toJSON(message: ChainConfigView): unknown {
    const obj: any = {};
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.chainType !== "") {
      obj.chainType = message.chainType;
    }
    if (message.bridgeContract !== "") {
      obj.bridgeContract = message.bridgeContract;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.minConfirmations !== 0) {
      obj.minConfirmations = Math.round(message.minConfirmations);
    }
    if (message.architecture !== "") {
      obj.architecture = message.architecture;
    }
    if (message.ibcChannelId !== "") {
      obj.ibcChannelId = message.ibcChannelId;
    }
    if (message.ibcPortId !== "") {
      obj.ibcPortId = message.ibcPortId;
    }
    return obj;
  },

  create(base?: DeepPartial<ChainConfigView>): ChainConfigView {
    return ChainConfigView.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ChainConfigView>): ChainConfigView {
    const message = createBaseChainConfigView();
    message.chainId = object.chainId ?? "";
    message.name = object.name ?? "";
    message.chainType = object.chainType ?? "";
    message.bridgeContract = object.bridgeContract ?? "";
    message.status = object.status ?? "";
    message.minConfirmations = object.minConfirmations ?? 0;
    message.architecture = object.architecture ?? "";
    message.ibcChannelId = object.ibcChannelId ?? "";
    message.ibcPortId = object.ibcPortId ?? "";
    return message;
  },
};

function createBaseBridgeValidatorView(): BridgeValidatorView {
  return { address: "", supportedChains: [], reputation: "", active: false, registeredAt: "0" };
}

export const BridgeValidatorView: MessageFns<BridgeValidatorView> = {
  encode(message: BridgeValidatorView, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    for (const v of message.supportedChains) {
      writer.uint32(18).string(v!);
    }
    if (message.reputation !== "") {
      writer.uint32(26).string(message.reputation);
    }
    if (message.active !== false) {
      writer.uint32(32).bool(message.active);
    }
    if (message.registeredAt !== "0") {
      writer.uint32(40).int64(message.registeredAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BridgeValidatorView {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBridgeValidatorView();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.supportedChains.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reputation = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.registeredAt = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BridgeValidatorView {
    return {
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      supportedChains: globalThis.Array.isArray(object?.supportedChains)
        ? object.supportedChains.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.supported_chains)
        ? object.supported_chains.map((e: any) => globalThis.String(e))
        : [],
      reputation: isSet(object.reputation) ? globalThis.String(object.reputation) : "",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
      registeredAt: isSet(object.registeredAt)
        ? globalThis.String(object.registeredAt)
        : isSet(object.registered_at)
        ? globalThis.String(object.registered_at)
        : "0",
    };
  },

  toJSON(message: BridgeValidatorView): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.supportedChains?.length) {
      obj.supportedChains = message.supportedChains;
    }
    if (message.reputation !== "") {
      obj.reputation = message.reputation;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    if (message.registeredAt !== "0") {
      obj.registeredAt = message.registeredAt;
    }
    return obj;
  },

  create(base?: DeepPartial<BridgeValidatorView>): BridgeValidatorView {
    return BridgeValidatorView.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BridgeValidatorView>): BridgeValidatorView {
    const message = createBaseBridgeValidatorView();
    message.address = object.address ?? "";
    message.supportedChains = object.supportedChains?.map((e) => e) || [];
    message.reputation = object.reputation ?? "";
    message.active = object.active ?? false;
    message.registeredAt = object.registeredAt ?? "0";
    return message;
  },
};

function createBaseBridgeOperationView(): BridgeOperationView {
  return {
    id: "",
    type: "",
    sourceChain: "",
    destChain: "",
    sender: "",
    receiver: "",
    asset: "",
    amount: "",
    sourceTxHash: "",
    status: "",
  };
}

export const BridgeOperationView: MessageFns<BridgeOperationView> = {
  encode(message: BridgeOperationView, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.sourceChain !== "") {
      writer.uint32(26).string(message.sourceChain);
    }
    if (message.destChain !== "") {
      writer.uint32(34).string(message.destChain);
    }
    if (message.sender !== "") {
      writer.uint32(42).string(message.sender);
    }
    if (message.receiver !== "") {
      writer.uint32(50).string(message.receiver);
    }
    if (message.asset !== "") {
      writer.uint32(58).string(message.asset);
    }
    if (message.amount !== "") {
      writer.uint32(66).string(message.amount);
    }
    if (message.sourceTxHash !== "") {
      writer.uint32(74).string(message.sourceTxHash);
    }
    if (message.status !== "") {
      writer.uint32(82).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BridgeOperationView {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBridgeOperationView();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sourceChain = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.destChain = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.sender = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.receiver = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.asset = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.sourceTxHash = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BridgeOperationView {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      sourceChain: isSet(object.sourceChain)
        ? globalThis.String(object.sourceChain)
        : isSet(object.source_chain)
        ? globalThis.String(object.source_chain)
        : "",
      destChain: isSet(object.destChain)
        ? globalThis.String(object.destChain)
        : isSet(object.dest_chain)
        ? globalThis.String(object.dest_chain)
        : "",
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      receiver: isSet(object.receiver) ? globalThis.String(object.receiver) : "",
      asset: isSet(object.asset) ? globalThis.String(object.asset) : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      sourceTxHash: isSet(object.sourceTxHash)
        ? globalThis.String(object.sourceTxHash)
        : isSet(object.source_tx_hash)
        ? globalThis.String(object.source_tx_hash)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: BridgeOperationView): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.sourceChain !== "") {
      obj.sourceChain = message.sourceChain;
    }
    if (message.destChain !== "") {
      obj.destChain = message.destChain;
    }
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.receiver !== "") {
      obj.receiver = message.receiver;
    }
    if (message.asset !== "") {
      obj.asset = message.asset;
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.sourceTxHash !== "") {
      obj.sourceTxHash = message.sourceTxHash;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create(base?: DeepPartial<BridgeOperationView>): BridgeOperationView {
    return BridgeOperationView.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BridgeOperationView>): BridgeOperationView {
    const message = createBaseBridgeOperationView();
    message.id = object.id ?? "";
    message.type = object.type ?? "";
    message.sourceChain = object.sourceChain ?? "";
    message.destChain = object.destChain ?? "";
    message.sender = object.sender ?? "";
    message.receiver = object.receiver ?? "";
    message.asset = object.asset ?? "";
    message.amount = object.amount ?? "";
    message.sourceTxHash = object.sourceTxHash ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseQueryConfigRequest(): QueryConfigRequest {
  return {};
}

export const QueryConfigRequest: MessageFns<QueryConfigRequest> = {
  encode(_: QueryConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryConfigRequest {
    return {};
  },

  toJSON(_: QueryConfigRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<QueryConfigRequest>): QueryConfigRequest {
    return QueryConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<QueryConfigRequest>): QueryConfigRequest {
    const message = createBaseQueryConfigRequest();
    return message;
  },
};

function createBaseQueryConfigResponse(): QueryConfigResponse {
  return { config: undefined };
}

export const QueryConfigResponse: MessageFns<QueryConfigResponse> = {
  encode(message: QueryConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.config !== undefined) {
      BridgeConfigView.encode(message.config, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config = BridgeConfigView.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryConfigResponse {
    return { config: isSet(object.config) ? BridgeConfigView.fromJSON(object.config) : undefined };
  },

  toJSON(message: QueryConfigResponse): unknown {
    const obj: any = {};
    if (message.config !== undefined) {
      obj.config = BridgeConfigView.toJSON(message.config);
    }
    return obj;
  },

  create(base?: DeepPartial<QueryConfigResponse>): QueryConfigResponse {
    return QueryConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryConfigResponse>): QueryConfigResponse {
    const message = createBaseQueryConfigResponse();
    message.config = (object.config !== undefined && object.config !== null)
      ? BridgeConfigView.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseQueryChainConfigRequest(): QueryChainConfigRequest {
  return { chainId: "" };
}

export const QueryChainConfigRequest: MessageFns<QueryChainConfigRequest> = {
  encode(message: QueryChainConfigRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryChainConfigRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryChainConfigRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chainId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryChainConfigRequest {
    return {
      chainId: isSet(object.chainId)
        ? globalThis.String(object.chainId)
        : isSet(object.chain_id)
        ? globalThis.String(object.chain_id)
        : "",
    };
  },

  toJSON(message: QueryChainConfigRequest): unknown {
    const obj: any = {};
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    return obj;
  },

  create(base?: DeepPartial<QueryChainConfigRequest>): QueryChainConfigRequest {
    return QueryChainConfigRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryChainConfigRequest>): QueryChainConfigRequest {
    const message = createBaseQueryChainConfigRequest();
    message.chainId = object.chainId ?? "";
    return message;
  },
};

function createBaseQueryChainConfigResponse(): QueryChainConfigResponse {
  return { chain: undefined };
}

export const QueryChainConfigResponse: MessageFns<QueryChainConfigResponse> = {
  encode(message: QueryChainConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chain !== undefined) {
      ChainConfigView.encode(message.chain, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryChainConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryChainConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chain = ChainConfigView.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryChainConfigResponse {
    return { chain: isSet(object.chain) ? ChainConfigView.fromJSON(object.chain) : undefined };
  },

  toJSON(message: QueryChainConfigResponse): unknown {
    const obj: any = {};
    if (message.chain !== undefined) {
      obj.chain = ChainConfigView.toJSON(message.chain);
    }
    return obj;
  },

  create(base?: DeepPartial<QueryChainConfigResponse>): QueryChainConfigResponse {
    return QueryChainConfigResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryChainConfigResponse>): QueryChainConfigResponse {
    const message = createBaseQueryChainConfigResponse();
    message.chain = (object.chain !== undefined && object.chain !== null)
      ? ChainConfigView.fromPartial(object.chain)
      : undefined;
    return message;
  },
};

function createBaseQueryChainConfigsRequest(): QueryChainConfigsRequest {
  return {};
}

export const QueryChainConfigsRequest: MessageFns<QueryChainConfigsRequest> = {
  encode(_: QueryChainConfigsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryChainConfigsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryChainConfigsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryChainConfigsRequest {
    return {};
  },

  toJSON(_: QueryChainConfigsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<QueryChainConfigsRequest>): QueryChainConfigsRequest {
    return QueryChainConfigsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<QueryChainConfigsRequest>): QueryChainConfigsRequest {
    const message = createBaseQueryChainConfigsRequest();
    return message;
  },
};

function createBaseQueryChainConfigsResponse(): QueryChainConfigsResponse {
  return { chains: [] };
}

export const QueryChainConfigsResponse: MessageFns<QueryChainConfigsResponse> = {
  encode(message: QueryChainConfigsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.chains) {
      ChainConfigView.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryChainConfigsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryChainConfigsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chains.push(ChainConfigView.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryChainConfigsResponse {
    return {
      chains: globalThis.Array.isArray(object?.chains)
        ? object.chains.map((e: any) => ChainConfigView.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryChainConfigsResponse): unknown {
    const obj: any = {};
    if (message.chains?.length) {
      obj.chains = message.chains.map((e) => ChainConfigView.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<QueryChainConfigsResponse>): QueryChainConfigsResponse {
    return QueryChainConfigsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryChainConfigsResponse>): QueryChainConfigsResponse {
    const message = createBaseQueryChainConfigsResponse();
    message.chains = object.chains?.map((e) => ChainConfigView.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryValidatorRequest(): QueryValidatorRequest {
  return { address: "" };
}

export const QueryValidatorRequest: MessageFns<QueryValidatorRequest> = {
  encode(message: QueryValidatorRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.address !== "") {
      writer.uint32(10).string(message.address);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryValidatorRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryValidatorRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.address = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryValidatorRequest {
    return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
  },

  toJSON(message: QueryValidatorRequest): unknown {
    const obj: any = {};
    if (message.address !== "") {
      obj.address = message.address;
    }
    return obj;
  },

  create(base?: DeepPartial<QueryValidatorRequest>): QueryValidatorRequest {
    return QueryValidatorRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryValidatorRequest>): QueryValidatorRequest {
    const message = createBaseQueryValidatorRequest();
    message.address = object.address ?? "";
    return message;
  },
};

function createBaseQueryValidatorResponse(): QueryValidatorResponse {
  return { validator: undefined };
}

export const QueryValidatorResponse: MessageFns<QueryValidatorResponse> = {
  encode(message: QueryValidatorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.validator !== undefined) {
      BridgeValidatorView.encode(message.validator, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryValidatorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryValidatorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.validator = BridgeValidatorView.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryValidatorResponse {
    return { validator: isSet(object.validator) ? BridgeValidatorView.fromJSON(object.validator) : undefined };
  },

  toJSON(message: QueryValidatorResponse): unknown {
    const obj: any = {};
    if (message.validator !== undefined) {
      obj.validator = BridgeValidatorView.toJSON(message.validator);
    }
    return obj;
  },

  create(base?: DeepPartial<QueryValidatorResponse>): QueryValidatorResponse {
    return QueryValidatorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryValidatorResponse>): QueryValidatorResponse {
    const message = createBaseQueryValidatorResponse();
    message.validator = (object.validator !== undefined && object.validator !== null)
      ? BridgeValidatorView.fromPartial(object.validator)
      : undefined;
    return message;
  },
};

function createBaseQueryValidatorsRequest(): QueryValidatorsRequest {
  return {};
}

export const QueryValidatorsRequest: MessageFns<QueryValidatorsRequest> = {
  encode(_: QueryValidatorsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryValidatorsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryValidatorsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryValidatorsRequest {
    return {};
  },

  toJSON(_: QueryValidatorsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<QueryValidatorsRequest>): QueryValidatorsRequest {
    return QueryValidatorsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<QueryValidatorsRequest>): QueryValidatorsRequest {
    const message = createBaseQueryValidatorsRequest();
    return message;
  },
};

function createBaseQueryValidatorsResponse(): QueryValidatorsResponse {
  return { validators: [] };
}

export const QueryValidatorsResponse: MessageFns<QueryValidatorsResponse> = {
  encode(message: QueryValidatorsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.validators) {
      BridgeValidatorView.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryValidatorsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryValidatorsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.validators.push(BridgeValidatorView.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryValidatorsResponse {
    return {
      validators: globalThis.Array.isArray(object?.validators)
        ? object.validators.map((e: any) => BridgeValidatorView.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryValidatorsResponse): unknown {
    const obj: any = {};
    if (message.validators?.length) {
      obj.validators = message.validators.map((e) => BridgeValidatorView.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<QueryValidatorsResponse>): QueryValidatorsResponse {
    return QueryValidatorsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryValidatorsResponse>): QueryValidatorsResponse {
    const message = createBaseQueryValidatorsResponse();
    message.validators = object.validators?.map((e) => BridgeValidatorView.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryOperationRequest(): QueryOperationRequest {
  return { id: "" };
}

export const QueryOperationRequest: MessageFns<QueryOperationRequest> = {
  encode(message: QueryOperationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryOperationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryOperationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryOperationRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: QueryOperationRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<QueryOperationRequest>): QueryOperationRequest {
    return QueryOperationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryOperationRequest>): QueryOperationRequest {
    const message = createBaseQueryOperationRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseQueryOperationResponse(): QueryOperationResponse {
  return { operation: undefined };
}

export const QueryOperationResponse: MessageFns<QueryOperationResponse> = {
  encode(message: QueryOperationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operation !== undefined) {
      BridgeOperationView.encode(message.operation, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryOperationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryOperationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operation = BridgeOperationView.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryOperationResponse {
    return { operation: isSet(object.operation) ? BridgeOperationView.fromJSON(object.operation) : undefined };
  },

  toJSON(message: QueryOperationResponse): unknown {
    const obj: any = {};
    if (message.operation !== undefined) {
      obj.operation = BridgeOperationView.toJSON(message.operation);
    }
    return obj;
  },

  create(base?: DeepPartial<QueryOperationResponse>): QueryOperationResponse {
    return QueryOperationResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryOperationResponse>): QueryOperationResponse {
    const message = createBaseQueryOperationResponse();
    message.operation = (object.operation !== undefined && object.operation !== null)
      ? BridgeOperationView.fromPartial(object.operation)
      : undefined;
    return message;
  },
};

function createBaseQueryOperationsRequest(): QueryOperationsRequest {
  return {};
}

export const QueryOperationsRequest: MessageFns<QueryOperationsRequest> = {
  encode(_: QueryOperationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryOperationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryOperationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryOperationsRequest {
    return {};
  },

  toJSON(_: QueryOperationsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<QueryOperationsRequest>): QueryOperationsRequest {
    return QueryOperationsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<QueryOperationsRequest>): QueryOperationsRequest {
    const message = createBaseQueryOperationsRequest();
    return message;
  },
};

function createBaseQueryOperationsResponse(): QueryOperationsResponse {
  return { operations: [] };
}

export const QueryOperationsResponse: MessageFns<QueryOperationsResponse> = {
  encode(message: QueryOperationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.operations) {
      BridgeOperationView.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryOperationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryOperationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operations.push(BridgeOperationView.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryOperationsResponse {
    return {
      operations: globalThis.Array.isArray(object?.operations)
        ? object.operations.map((e: any) => BridgeOperationView.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryOperationsResponse): unknown {
    const obj: any = {};
    if (message.operations?.length) {
      obj.operations = message.operations.map((e) => BridgeOperationView.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<QueryOperationsResponse>): QueryOperationsResponse {
    return QueryOperationsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QueryOperationsResponse>): QueryOperationsResponse {
    const message = createBaseQueryOperationsResponse();
    message.operations = object.operations?.map((e) => BridgeOperationView.fromPartial(e)) || [];
    return message;
  },
};

/** Query defines the gRPC query service for the bridge module. */
export type QueryDefinition = typeof QueryDefinition;
export const QueryDefinition = {
  name: "Query",
  fullName: "qorechain.bridge.v1.Query",
  methods: {
    /** Config returns the global bridge config. */
    config: {
      name: "Config",
      requestType: QueryConfigRequest as typeof QueryConfigRequest,
      requestStream: false,
      responseType: QueryConfigResponse as typeof QueryConfigResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              29,
              18,
              27,
              47,
              113,
              111,
              114,
              101,
              99,
              104,
              97,
              105,
              110,
              47,
              98,
              114,
              105,
              100,
              103,
              101,
              47,
              118,
              49,
              47,
              99,
              111,
              110,
              102,
              105,
              103,
            ]) as Uint8Array,
          ],
        },
      },
    },
    /** ChainConfig returns a single chain config by ID. */
    chainConfig: {
      name: "ChainConfig",
      requestType: QueryChainConfigRequest as typeof QueryChainConfigRequest,
      requestStream: false,
      responseType: QueryChainConfigResponse as typeof QueryChainConfigResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              40,
              18,
              38,
              47,
              113,
              111,
              114,
              101,
              99,
              104,
              97,
              105,
              110,
              47,
              98,
              114,
              105,
              100,
              103,
              101,
              47,
              118,
              49,
              47,
              99,
              104,
              97,
              105,
              110,
              115,
              47,
              123,
              99,
              104,
              97,
              105,
              110,
              95,
              105,
              100,
              125,
            ]) as Uint8Array,
          ],
        },
      },
    },
    /** ChainConfigs lists all configured chains. */
    chainConfigs: {
      name: "ChainConfigs",
      requestType: QueryChainConfigsRequest as typeof QueryChainConfigsRequest,
      requestStream: false,
      responseType: QueryChainConfigsResponse as typeof QueryChainConfigsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              29,
              18,
              27,
              47,
              113,
              111,
              114,
              101,
              99,
              104,
              97,
              105,
              110,
              47,
              98,
              114,
              105,
              100,
              103,
              101,
              47,
              118,
              49,
              47,
              99,
              104,
              97,
              105,
              110,
              115,
            ]) as Uint8Array,
          ],
        },
      },
    },
    /** Validator returns a single bridge validator by address. */
    validator: {
      name: "Validator",
      requestType: QueryValidatorRequest as typeof QueryValidatorRequest,
      requestStream: false,
      responseType: QueryValidatorResponse as typeof QueryValidatorResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              43,
              18,
              41,
              47,
              113,
              111,
              114,
              101,
              99,
              104,
              97,
              105,
              110,
              47,
              98,
              114,
              105,
              100,
              103,
              101,
              47,
              118,
              49,
              47,
              118,
              97,
              108,
              105,
              100,
              97,
              116,
              111,
              114,
              115,
              47,
              123,
              97,
              100,
              100,
              114,
              101,
              115,
              115,
              125,
            ]) as Uint8Array,
          ],
        },
      },
    },
    /** Validators lists all bridge validators. */
    validators: {
      name: "Validators",
      requestType: QueryValidatorsRequest as typeof QueryValidatorsRequest,
      requestStream: false,
      responseType: QueryValidatorsResponse as typeof QueryValidatorsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              33,
              18,
              31,
              47,
              113,
              111,
              114,
              101,
              99,
              104,
              97,
              105,
              110,
              47,
              98,
              114,
              105,
              100,
              103,
              101,
              47,
              118,
              49,
              47,
              118,
              97,
              108,
              105,
              100,
              97,
              116,
              111,
              114,
              115,
            ]) as Uint8Array,
          ],
        },
      },
    },
    /** Operation returns a single bridge operation by ID. */
    operation: {
      name: "Operation",
      requestType: QueryOperationRequest as typeof QueryOperationRequest,
      requestStream: false,
      responseType: QueryOperationResponse as typeof QueryOperationResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              38,
              18,
              36,
              47,
              113,
              111,
              114,
              101,
              99,
              104,
              97,
              105,
              110,
              47,
              98,
              114,
              105,
              100,
              103,
              101,
              47,
              118,
              49,
              47,
              111,
              112,
              101,
              114,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              105,
              100,
              125,
            ]) as Uint8Array,
          ],
        },
      },
    },
    /** Operations lists all bridge operations. */
    operations: {
      name: "Operations",
      requestType: QueryOperationsRequest as typeof QueryOperationsRequest,
      requestStream: false,
      responseType: QueryOperationsResponse as typeof QueryOperationsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              33,
              18,
              31,
              47,
              113,
              111,
              114,
              101,
              99,
              104,
              97,
              105,
              110,
              47,
              98,
              114,
              105,
              100,
              103,
              101,
              47,
              118,
              49,
              47,
              111,
              112,
              101,
              114,
              97,
              116,
              105,
              111,
              110,
              115,
            ]) as Uint8Array,
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
