// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cosmos/base/query/v1beta1/pagination.proto
// Protobuf Java Version: 4.35.1

package cosmos.base.query.v1beta1;

@com.google.protobuf.Generated
public final class Pagination extends com.google.protobuf.GeneratedFile {
  private Pagination() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Pagination");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PageRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.base.query.v1beta1.PageRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * key is a value returned in PageResponse.next_key to begin
     * querying the next page most efficiently. Only one of offset or key
     * should be set.
     * </pre>
     *
     * <code>bytes key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    com.google.protobuf.ByteString getKey();

    /**
     * <pre>
     * offset is a numeric offset that can be used when key is unavailable.
     * It is less efficient than using key. Only one of offset or key should
     * be set.
     * </pre>
     *
     * <code>uint64 offset = 2 [json_name = "offset"];</code>
     * @return The offset.
     */
    long getOffset();

    /**
     * <pre>
     * limit is the total number of results to be returned in the result page.
     * If left empty it will default to a value to be set by each app.
     * </pre>
     *
     * <code>uint64 limit = 3 [json_name = "limit"];</code>
     * @return The limit.
     */
    long getLimit();

    /**
     * <pre>
     * count_total is set to true  to indicate that the result set should include
     * a count of the total number of items available for pagination in UIs.
     * count_total is only respected when offset is used. It is ignored when key
     * is set.
     * </pre>
     *
     * <code>bool count_total = 4 [json_name = "countTotal"];</code>
     * @return The countTotal.
     */
    boolean getCountTotal();

    /**
     * <pre>
     * reverse is set to true if results are to be returned in the descending order.
     * </pre>
     *
     * <code>bool reverse = 5 [json_name = "reverse", (.cosmos_proto.field_added_in) = "cosmos-sdk 0.43"];</code>
     * @return The reverse.
     */
    boolean getReverse();
  }
  /**
   * <pre>
   * PageRequest is to be embedded in gRPC request messages for efficient
   * pagination. Ex:
   *
   * message SomeRequest {
   * Foo some_parameter = 1;
   * PageRequest pagination = 2;
   * }
   * </pre>
   *
   * Protobuf type {@code cosmos.base.query.v1beta1.PageRequest}
   */
  public static final class PageRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cosmos.base.query.v1beta1.PageRequest)
      PageRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "PageRequest");
    }
    // Use PageRequest.newBuilder() to construct.
    private PageRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PageRequest() {
      key_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.base.query.v1beta1.Pagination.PageRequest.class, cosmos.base.query.v1beta1.Pagination.PageRequest.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * key is a value returned in PageResponse.next_key to begin
     * querying the next page most efficiently. Only one of offset or key
     * should be set.
     * </pre>
     *
     * <code>bytes key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }

    public static final int OFFSET_FIELD_NUMBER = 2;
    private long offset_ = 0L;
    /**
     * <pre>
     * offset is a numeric offset that can be used when key is unavailable.
     * It is less efficient than using key. Only one of offset or key should
     * be set.
     * </pre>
     *
     * <code>uint64 offset = 2 [json_name = "offset"];</code>
     * @return The offset.
     */
    @java.lang.Override
    public long getOffset() {
      return offset_;
    }

    public static final int LIMIT_FIELD_NUMBER = 3;
    private long limit_ = 0L;
    /**
     * <pre>
     * limit is the total number of results to be returned in the result page.
     * If left empty it will default to a value to be set by each app.
     * </pre>
     *
     * <code>uint64 limit = 3 [json_name = "limit"];</code>
     * @return The limit.
     */
    @java.lang.Override
    public long getLimit() {
      return limit_;
    }

    public static final int COUNT_TOTAL_FIELD_NUMBER = 4;
    private boolean countTotal_ = false;
    /**
     * <pre>
     * count_total is set to true  to indicate that the result set should include
     * a count of the total number of items available for pagination in UIs.
     * count_total is only respected when offset is used. It is ignored when key
     * is set.
     * </pre>
     *
     * <code>bool count_total = 4 [json_name = "countTotal"];</code>
     * @return The countTotal.
     */
    @java.lang.Override
    public boolean getCountTotal() {
      return countTotal_;
    }

    public static final int REVERSE_FIELD_NUMBER = 5;
    private boolean reverse_ = false;
    /**
     * <pre>
     * reverse is set to true if results are to be returned in the descending order.
     * </pre>
     *
     * <code>bool reverse = 5 [json_name = "reverse", (.cosmos_proto.field_added_in) = "cosmos-sdk 0.43"];</code>
     * @return The reverse.
     */
    @java.lang.Override
    public boolean getReverse() {
      return reverse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!key_.isEmpty()) {
        output.writeBytes(1, key_);
      }
      if (offset_ != 0L) {
        output.writeUInt64(2, offset_);
      }
      if (limit_ != 0L) {
        output.writeUInt64(3, limit_);
      }
      if (countTotal_ != false) {
        output.writeBool(4, countTotal_);
      }
      if (reverse_ != false) {
        output.writeBool(5, reverse_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!key_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, key_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, offset_);
      }
      if (limit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, limit_);
      }
      if (countTotal_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, countTotal_);
      }
      if (reverse_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, reverse_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.base.query.v1beta1.Pagination.PageRequest)) {
        return super.equals(obj);
      }
      cosmos.base.query.v1beta1.Pagination.PageRequest other = (cosmos.base.query.v1beta1.Pagination.PageRequest) obj;

      if (!getKey()
          .equals(other.getKey())) return false;
      if (getOffset()
          != other.getOffset()) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (getCountTotal()
          != other.getCountTotal()) return false;
      if (getReverse()
          != other.getReverse()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLimit());
      hash = (37 * hash) + COUNT_TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCountTotal());
      hash = (37 * hash) + REVERSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReverse());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.base.query.v1beta1.Pagination.PageRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PageRequest is to be embedded in gRPC request messages for efficient
     * pagination. Ex:
     *
     * message SomeRequest {
     * Foo some_parameter = 1;
     * PageRequest pagination = 2;
     * }
     * </pre>
     *
     * Protobuf type {@code cosmos.base.query.v1beta1.PageRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.base.query.v1beta1.PageRequest)
        cosmos.base.query.v1beta1.Pagination.PageRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.base.query.v1beta1.Pagination.PageRequest.class, cosmos.base.query.v1beta1.Pagination.PageRequest.Builder.class);
      }

      // Construct using cosmos.base.query.v1beta1.Pagination.PageRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        key_ = com.google.protobuf.ByteString.EMPTY;
        offset_ = 0L;
        limit_ = 0L;
        countTotal_ = false;
        reverse_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageRequest_descriptor;
      }

      @java.lang.Override
      public cosmos.base.query.v1beta1.Pagination.PageRequest getDefaultInstanceForType() {
        return cosmos.base.query.v1beta1.Pagination.PageRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.base.query.v1beta1.Pagination.PageRequest build() {
        cosmos.base.query.v1beta1.Pagination.PageRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.base.query.v1beta1.Pagination.PageRequest buildPartial() {
        cosmos.base.query.v1beta1.Pagination.PageRequest result = new cosmos.base.query.v1beta1.Pagination.PageRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cosmos.base.query.v1beta1.Pagination.PageRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.key_ = key_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.offset_ = offset_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.limit_ = limit_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.countTotal_ = countTotal_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.reverse_ = reverse_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.base.query.v1beta1.Pagination.PageRequest) {
          return mergeFrom((cosmos.base.query.v1beta1.Pagination.PageRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.base.query.v1beta1.Pagination.PageRequest other) {
        if (other == cosmos.base.query.v1beta1.Pagination.PageRequest.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          setKey(other.getKey());
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (other.getLimit() != 0L) {
          setLimit(other.getLimit());
        }
        if (other.getCountTotal() != false) {
          setCountTotal(other.getCountTotal());
        }
        if (other.getReverse() != false) {
          setReverse(other.getReverse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                offset_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                limit_ = input.readUInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                countTotal_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                reverse_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * key is a value returned in PageResponse.next_key to begin
       * querying the next page most efficiently. Only one of offset or key
       * should be set.
       * </pre>
       *
       * <code>bytes key = 1 [json_name = "key"];</code>
       * @return The key.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKey() {
        return key_;
      }
      /**
       * <pre>
       * key is a value returned in PageResponse.next_key to begin
       * querying the next page most efficiently. Only one of offset or key
       * should be set.
       * </pre>
       *
       * <code>bytes key = 1 [json_name = "key"];</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * key is a value returned in PageResponse.next_key to begin
       * querying the next page most efficiently. Only one of offset or key
       * should be set.
       * </pre>
       *
       * <code>bytes key = 1 [json_name = "key"];</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <pre>
       * offset is a numeric offset that can be used when key is unavailable.
       * It is less efficient than using key. Only one of offset or key should
       * be set.
       * </pre>
       *
       * <code>uint64 offset = 2 [json_name = "offset"];</code>
       * @return The offset.
       */
      @java.lang.Override
      public long getOffset() {
        return offset_;
      }
      /**
       * <pre>
       * offset is a numeric offset that can be used when key is unavailable.
       * It is less efficient than using key. Only one of offset or key should
       * be set.
       * </pre>
       *
       * <code>uint64 offset = 2 [json_name = "offset"];</code>
       * @param value The offset to set.
       * @return This builder for chaining.
       */
      public Builder setOffset(long value) {

        offset_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * offset is a numeric offset that can be used when key is unavailable.
       * It is less efficient than using key. Only one of offset or key should
       * be set.
       * </pre>
       *
       * <code>uint64 offset = 2 [json_name = "offset"];</code>
       * @return This builder for chaining.
       */
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offset_ = 0L;
        onChanged();
        return this;
      }

      private long limit_ ;
      /**
       * <pre>
       * limit is the total number of results to be returned in the result page.
       * If left empty it will default to a value to be set by each app.
       * </pre>
       *
       * <code>uint64 limit = 3 [json_name = "limit"];</code>
       * @return The limit.
       */
      @java.lang.Override
      public long getLimit() {
        return limit_;
      }
      /**
       * <pre>
       * limit is the total number of results to be returned in the result page.
       * If left empty it will default to a value to be set by each app.
       * </pre>
       *
       * <code>uint64 limit = 3 [json_name = "limit"];</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(long value) {

        limit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * limit is the total number of results to be returned in the result page.
       * If left empty it will default to a value to be set by each app.
       * </pre>
       *
       * <code>uint64 limit = 3 [json_name = "limit"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        limit_ = 0L;
        onChanged();
        return this;
      }

      private boolean countTotal_ ;
      /**
       * <pre>
       * count_total is set to true  to indicate that the result set should include
       * a count of the total number of items available for pagination in UIs.
       * count_total is only respected when offset is used. It is ignored when key
       * is set.
       * </pre>
       *
       * <code>bool count_total = 4 [json_name = "countTotal"];</code>
       * @return The countTotal.
       */
      @java.lang.Override
      public boolean getCountTotal() {
        return countTotal_;
      }
      /**
       * <pre>
       * count_total is set to true  to indicate that the result set should include
       * a count of the total number of items available for pagination in UIs.
       * count_total is only respected when offset is used. It is ignored when key
       * is set.
       * </pre>
       *
       * <code>bool count_total = 4 [json_name = "countTotal"];</code>
       * @param value The countTotal to set.
       * @return This builder for chaining.
       */
      public Builder setCountTotal(boolean value) {

        countTotal_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * count_total is set to true  to indicate that the result set should include
       * a count of the total number of items available for pagination in UIs.
       * count_total is only respected when offset is used. It is ignored when key
       * is set.
       * </pre>
       *
       * <code>bool count_total = 4 [json_name = "countTotal"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCountTotal() {
        bitField0_ = (bitField0_ & ~0x00000008);
        countTotal_ = false;
        onChanged();
        return this;
      }

      private boolean reverse_ ;
      /**
       * <pre>
       * reverse is set to true if results are to be returned in the descending order.
       * </pre>
       *
       * <code>bool reverse = 5 [json_name = "reverse", (.cosmos_proto.field_added_in) = "cosmos-sdk 0.43"];</code>
       * @return The reverse.
       */
      @java.lang.Override
      public boolean getReverse() {
        return reverse_;
      }
      /**
       * <pre>
       * reverse is set to true if results are to be returned in the descending order.
       * </pre>
       *
       * <code>bool reverse = 5 [json_name = "reverse", (.cosmos_proto.field_added_in) = "cosmos-sdk 0.43"];</code>
       * @param value The reverse to set.
       * @return This builder for chaining.
       */
      public Builder setReverse(boolean value) {

        reverse_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * reverse is set to true if results are to be returned in the descending order.
       * </pre>
       *
       * <code>bool reverse = 5 [json_name = "reverse", (.cosmos_proto.field_added_in) = "cosmos-sdk 0.43"];</code>
       * @return This builder for chaining.
       */
      public Builder clearReverse() {
        bitField0_ = (bitField0_ & ~0x00000010);
        reverse_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cosmos.base.query.v1beta1.PageRequest)
    }

    // @@protoc_insertion_point(class_scope:cosmos.base.query.v1beta1.PageRequest)
    private static final cosmos.base.query.v1beta1.Pagination.PageRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.base.query.v1beta1.Pagination.PageRequest();
    }

    public static cosmos.base.query.v1beta1.Pagination.PageRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageRequest>
        PARSER = new com.google.protobuf.AbstractParser<PageRequest>() {
      @java.lang.Override
      public PageRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PageRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PageRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.base.query.v1beta1.Pagination.PageRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PageResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.base.query.v1beta1.PageResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * next_key is the key to be passed to PageRequest.key to
     * query the next page most efficiently. It will be empty if
     * there are no more results.
     * </pre>
     *
     * <code>bytes next_key = 1 [json_name = "nextKey"];</code>
     * @return The nextKey.
     */
    com.google.protobuf.ByteString getNextKey();

    /**
     * <pre>
     * total is total number of results available if PageRequest.count_total
     * was set, its value is undefined otherwise
     * </pre>
     *
     * <code>uint64 total = 2 [json_name = "total"];</code>
     * @return The total.
     */
    long getTotal();
  }
  /**
   * <pre>
   * PageResponse is to be embedded in gRPC response messages where the
   * corresponding request message has used PageRequest.
   *
   * message SomeResponse {
   * repeated Bar results = 1;
   * PageResponse page = 2;
   * }
   * </pre>
   *
   * Protobuf type {@code cosmos.base.query.v1beta1.PageResponse}
   */
  public static final class PageResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cosmos.base.query.v1beta1.PageResponse)
      PageResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "PageResponse");
    }
    // Use PageResponse.newBuilder() to construct.
    private PageResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PageResponse() {
      nextKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.base.query.v1beta1.Pagination.PageResponse.class, cosmos.base.query.v1beta1.Pagination.PageResponse.Builder.class);
    }

    public static final int NEXT_KEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString nextKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * next_key is the key to be passed to PageRequest.key to
     * query the next page most efficiently. It will be empty if
     * there are no more results.
     * </pre>
     *
     * <code>bytes next_key = 1 [json_name = "nextKey"];</code>
     * @return The nextKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNextKey() {
      return nextKey_;
    }

    public static final int TOTAL_FIELD_NUMBER = 2;
    private long total_ = 0L;
    /**
     * <pre>
     * total is total number of results available if PageRequest.count_total
     * was set, its value is undefined otherwise
     * </pre>
     *
     * <code>uint64 total = 2 [json_name = "total"];</code>
     * @return The total.
     */
    @java.lang.Override
    public long getTotal() {
      return total_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!nextKey_.isEmpty()) {
        output.writeBytes(1, nextKey_);
      }
      if (total_ != 0L) {
        output.writeUInt64(2, total_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!nextKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, nextKey_);
      }
      if (total_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, total_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.base.query.v1beta1.Pagination.PageResponse)) {
        return super.equals(obj);
      }
      cosmos.base.query.v1beta1.Pagination.PageResponse other = (cosmos.base.query.v1beta1.Pagination.PageResponse) obj;

      if (!getNextKey()
          .equals(other.getNextKey())) return false;
      if (getTotal()
          != other.getTotal()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NEXT_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getNextKey().hashCode();
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTotal());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.base.query.v1beta1.Pagination.PageResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.base.query.v1beta1.Pagination.PageResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * PageResponse is to be embedded in gRPC response messages where the
     * corresponding request message has used PageRequest.
     *
     * message SomeResponse {
     * repeated Bar results = 1;
     * PageResponse page = 2;
     * }
     * </pre>
     *
     * Protobuf type {@code cosmos.base.query.v1beta1.PageResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.base.query.v1beta1.PageResponse)
        cosmos.base.query.v1beta1.Pagination.PageResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.base.query.v1beta1.Pagination.PageResponse.class, cosmos.base.query.v1beta1.Pagination.PageResponse.Builder.class);
      }

      // Construct using cosmos.base.query.v1beta1.Pagination.PageResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nextKey_ = com.google.protobuf.ByteString.EMPTY;
        total_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.base.query.v1beta1.Pagination.internal_static_cosmos_base_query_v1beta1_PageResponse_descriptor;
      }

      @java.lang.Override
      public cosmos.base.query.v1beta1.Pagination.PageResponse getDefaultInstanceForType() {
        return cosmos.base.query.v1beta1.Pagination.PageResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.base.query.v1beta1.Pagination.PageResponse build() {
        cosmos.base.query.v1beta1.Pagination.PageResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.base.query.v1beta1.Pagination.PageResponse buildPartial() {
        cosmos.base.query.v1beta1.Pagination.PageResponse result = new cosmos.base.query.v1beta1.Pagination.PageResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(cosmos.base.query.v1beta1.Pagination.PageResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nextKey_ = nextKey_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.total_ = total_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.base.query.v1beta1.Pagination.PageResponse) {
          return mergeFrom((cosmos.base.query.v1beta1.Pagination.PageResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.base.query.v1beta1.Pagination.PageResponse other) {
        if (other == cosmos.base.query.v1beta1.Pagination.PageResponse.getDefaultInstance()) return this;
        if (!other.getNextKey().isEmpty()) {
          setNextKey(other.getNextKey());
        }
        if (other.getTotal() != 0L) {
          setTotal(other.getTotal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nextKey_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                total_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString nextKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * next_key is the key to be passed to PageRequest.key to
       * query the next page most efficiently. It will be empty if
       * there are no more results.
       * </pre>
       *
       * <code>bytes next_key = 1 [json_name = "nextKey"];</code>
       * @return The nextKey.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getNextKey() {
        return nextKey_;
      }
      /**
       * <pre>
       * next_key is the key to be passed to PageRequest.key to
       * query the next page most efficiently. It will be empty if
       * there are no more results.
       * </pre>
       *
       * <code>bytes next_key = 1 [json_name = "nextKey"];</code>
       * @param value The nextKey to set.
       * @return This builder for chaining.
       */
      public Builder setNextKey(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        nextKey_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * next_key is the key to be passed to PageRequest.key to
       * query the next page most efficiently. It will be empty if
       * there are no more results.
       * </pre>
       *
       * <code>bytes next_key = 1 [json_name = "nextKey"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNextKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nextKey_ = getDefaultInstance().getNextKey();
        onChanged();
        return this;
      }

      private long total_ ;
      /**
       * <pre>
       * total is total number of results available if PageRequest.count_total
       * was set, its value is undefined otherwise
       * </pre>
       *
       * <code>uint64 total = 2 [json_name = "total"];</code>
       * @return The total.
       */
      @java.lang.Override
      public long getTotal() {
        return total_;
      }
      /**
       * <pre>
       * total is total number of results available if PageRequest.count_total
       * was set, its value is undefined otherwise
       * </pre>
       *
       * <code>uint64 total = 2 [json_name = "total"];</code>
       * @param value The total to set.
       * @return This builder for chaining.
       */
      public Builder setTotal(long value) {

        total_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * total is total number of results available if PageRequest.count_total
       * was set, its value is undefined otherwise
       * </pre>
       *
       * <code>uint64 total = 2 [json_name = "total"];</code>
       * @return This builder for chaining.
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        total_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cosmos.base.query.v1beta1.PageResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.base.query.v1beta1.PageResponse)
    private static final cosmos.base.query.v1beta1.Pagination.PageResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.base.query.v1beta1.Pagination.PageResponse();
    }

    public static cosmos.base.query.v1beta1.Pagination.PageResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageResponse>
        PARSER = new com.google.protobuf.AbstractParser<PageResponse>() {
      @java.lang.Override
      public PageResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PageResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PageResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.base.query.v1beta1.Pagination.PageResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_base_query_v1beta1_PageRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cosmos_base_query_v1beta1_PageRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_base_query_v1beta1_PageResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cosmos_base_query_v1beta1_PageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*cosmos/base/query/v1beta1/pagination.p" +
      "roto\022\031cosmos.base.query.v1beta1\032\031cosmos_" +
      "proto/cosmos.proto\"\235\001\n\013PageRequest\022\020\n\003ke" +
      "y\030\001 \001(\014R\003key\022\026\n\006offset\030\002 \001(\004R\006offset\022\024\n\005" +
      "limit\030\003 \001(\004R\005limit\022\037\n\013count_total\030\004 \001(\010R" +
      "\ncountTotal\022-\n\007reverse\030\005 \001(\010B\023\332\264-\017cosmos" +
      "-sdk 0.43R\007reverse\"?\n\014PageResponse\022\031\n\010ne" +
      "xt_key\030\001 \001(\014R\007nextKey\022\024\n\005total\030\002 \001(\004R\005to" +
      "talB*Z(github.com/cosmos/cosmos-sdk/type" +
      "s/queryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cosmos_proto.Cosmos.getDescriptor(),
        });
    internal_static_cosmos_base_query_v1beta1_PageRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_cosmos_base_query_v1beta1_PageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cosmos_base_query_v1beta1_PageRequest_descriptor,
        new java.lang.String[] { "Key", "Offset", "Limit", "CountTotal", "Reverse", });
    internal_static_cosmos_base_query_v1beta1_PageResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_cosmos_base_query_v1beta1_PageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cosmos_base_query_v1beta1_PageResponse_descriptor,
        new java.lang.String[] { "NextKey", "Total", });
    descriptor.resolveAllFeaturesImmutable();
    cosmos_proto.Cosmos.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(cosmos_proto.Cosmos.fieldAddedIn);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
