// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/pqc/v1/query.proto

package pqcv1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAccountRequest struct {
	// address is the bech32 account address whose PQC key is requested.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAccountRequest) Reset()         { *m = QueryAccountRequest{} }
func (m *QueryAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAccountRequest) ProtoMessage()    {}
func (*QueryAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{0}
}
func (m *QueryAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountRequest.Merge(m, src)
}
func (m *QueryAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountRequest proto.InternalMessageInfo

func (m *QueryAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAccountResponse struct {
	// found reports whether the account has a registered PQC key.
	Found   bool            `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Account *PQCAccountView `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *QueryAccountResponse) Reset()         { *m = QueryAccountResponse{} }
func (m *QueryAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAccountResponse) ProtoMessage()    {}
func (*QueryAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{1}
}
func (m *QueryAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountResponse.Merge(m, src)
}
func (m *QueryAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountResponse proto.InternalMessageInfo

func (m *QueryAccountResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *QueryAccountResponse) GetAccount() *PQCAccountView {
	if m != nil {
		return m.Account
	}
	return nil
}

// PQCAccountView is the query-facing view of a registered PQC account.
type PQCAccountView struct {
	Address              string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey            []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AlgorithmId          uint32 `protobuf:"varint,3,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmName        string `protobuf:"bytes,4,opt,name=algorithm_name,json=algorithmName,proto3" json:"algorithm_name,omitempty"`
	EcdsaPubkey          []byte `protobuf:"bytes,5,opt,name=ecdsa_pubkey,json=ecdsaPubkey,proto3" json:"ecdsa_pubkey,omitempty"`
	KeyType              string `protobuf:"bytes,6,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	CreatedAtHeight      int64  `protobuf:"varint,7,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"`
	MigrationPublicKey   []byte `protobuf:"bytes,8,opt,name=migration_public_key,json=migrationPublicKey,proto3" json:"migration_public_key,omitempty"`
	MigrationAlgorithmId uint32 `protobuf:"varint,9,opt,name=migration_algorithm_id,json=migrationAlgorithmId,proto3" json:"migration_algorithm_id,omitempty"`
}

func (m *PQCAccountView) Reset()         { *m = PQCAccountView{} }
func (m *PQCAccountView) String() string { return proto.CompactTextString(m) }
func (*PQCAccountView) ProtoMessage()    {}
func (*PQCAccountView) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{2}
}
func (m *PQCAccountView) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PQCAccountView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PQCAccountView.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PQCAccountView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQCAccountView.Merge(m, src)
}
func (m *PQCAccountView) XXX_Size() int {
	return m.Size()
}
func (m *PQCAccountView) XXX_DiscardUnknown() {
	xxx_messageInfo_PQCAccountView.DiscardUnknown(m)
}

var xxx_messageInfo_PQCAccountView proto.InternalMessageInfo

func (m *PQCAccountView) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PQCAccountView) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PQCAccountView) GetAlgorithmId() uint32 {
	if m != nil {
		return m.AlgorithmId
	}
	return 0
}

func (m *PQCAccountView) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

func (m *PQCAccountView) GetEcdsaPubkey() []byte {
	if m != nil {
		return m.EcdsaPubkey
	}
	return nil
}

func (m *PQCAccountView) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *PQCAccountView) GetCreatedAtHeight() int64 {
	if m != nil {
		return m.CreatedAtHeight
	}
	return 0
}

func (m *PQCAccountView) GetMigrationPublicKey() []byte {
	if m != nil {
		return m.MigrationPublicKey
	}
	return nil
}

func (m *PQCAccountView) GetMigrationAlgorithmId() uint32 {
	if m != nil {
		return m.MigrationAlgorithmId
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryAccountRequest)(nil), "qorechain.pqc.v1.QueryAccountRequest")
	proto.RegisterType((*QueryAccountResponse)(nil), "qorechain.pqc.v1.QueryAccountResponse")
	proto.RegisterType((*PQCAccountView)(nil), "qorechain.pqc.v1.PQCAccountView")
}

func init() { proto.RegisterFile("qorechain/pqc/v1/query.proto", fileDescriptor_0f221b60dbf809b5) }

var fileDescriptor_0f221b60dbf809b5 = []byte{
	// 571 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4d, 0x8b, 0xd3, 0x40,
	0x18, 0xc7, 0x77, 0xb2, 0xee, 0x76, 0x77, 0xf6, 0xc5, 0x75, 0x2c, 0x12, 0x97, 0x1a, 0x6a, 0xa5,
	0x52, 0x14, 0x13, 0xb3, 0x7a, 0xaa, 0xa7, 0xd6, 0x83, 0x8a, 0x28, 0x69, 0xd0, 0x22, 0x52, 0x08,
	0xd3, 0xc9, 0x98, 0x84, 0x36, 0x99, 0xbc, 0x4c, 0x2a, 0x41, 0xbc, 0x08, 0x9e, 0x15, 0xfc, 0x06,
	0x1e, 0xfd, 0x24, 0xe2, 0x69, 0xc1, 0x8b, 0x47, 0x69, 0xf5, 0xe2, 0xd5, 0x2f, 0x20, 0x9d, 0x74,
	0xd3, 0x76, 0xab, 0x78, 0xcb, 0xfc, 0x9f, 0x97, 0xdf, 0xf3, 0xe4, 0xff, 0xc0, 0x4a, 0xc4, 0x62,
	0x4a, 0x5c, 0xec, 0x05, 0x5a, 0x18, 0x11, 0x6d, 0xa4, 0x6b, 0x51, 0x4a, 0xe3, 0x4c, 0x0d, 0x63,
	0xc6, 0x19, 0x3a, 0x28, 0xa2, 0x6a, 0x18, 0x11, 0x75, 0xa4, 0x1f, 0x56, 0x1c, 0xc6, 0x9c, 0x21,
	0xd5, 0x70, 0xe8, 0x69, 0x38, 0x08, 0x18, 0xc7, 0xdc, 0x63, 0x41, 0x92, 0xe7, 0xd7, 0x34, 0x78,
	0xbe, 0x33, 0x2d, 0x6f, 0x11, 0xc2, 0xd2, 0x80, 0x9b, 0x34, 0x4a, 0x69, 0xc2, 0x91, 0x0c, 0x4b,
	0xd8, 0xb6, 0x63, 0x9a, 0x24, 0x32, 0xa8, 0x82, 0xc6, 0xb6, 0x79, 0xf2, 0xac, 0xb9, 0xb0, 0xbc,
	0x5c, 0x90, 0x84, 0x2c, 0x48, 0x28, 0x2a, 0xc3, 0x8d, 0x17, 0x2c, 0x0d, 0x6c, 0x91, 0xbf, 0x65,
	0xe6, 0x0f, 0xd4, 0x84, 0x25, 0x9c, 0x27, 0xca, 0x52, 0x15, 0x34, 0x76, 0x8e, 0xaa, 0xea, 0xe9,
	0x01, 0x55, 0xa3, 0x73, 0x77, 0xd6, 0xac, 0xeb, 0xd1, 0x97, 0xe6, 0x49, 0x41, 0xed, 0xa7, 0x04,
	0xf7, 0x97, 0x63, 0xff, 0x1e, 0x0b, 0x5d, 0x82, 0x30, 0x4c, 0xfb, 0x43, 0x8f, 0x58, 0x03, 0x9a,
	0x09, 0xd6, 0xae, 0xb9, 0x9d, 0x2b, 0x0f, 0x69, 0x86, 0x2e, 0xc3, 0x5d, 0x3c, 0x74, 0x58, 0xec,
	0x71, 0xd7, 0xb7, 0x3c, 0x5b, 0x5e, 0xaf, 0x82, 0xc6, 0x9e, 0xb9, 0x53, 0x68, 0x0f, 0x6c, 0x54,
	0x87, 0xfb, 0xf3, 0x94, 0x00, 0xfb, 0x54, 0x3e, 0x23, 0x10, 0x7b, 0x85, 0xfa, 0x18, 0xfb, 0x74,
	0xda, 0x89, 0x12, 0x3b, 0xc1, 0x56, 0x98, 0xf6, 0xa7, 0xa8, 0x0d, 0x81, 0xda, 0x11, 0x9a, 0x21,
	0x24, 0x74, 0x11, 0x6e, 0x0d, 0x68, 0x66, 0xf1, 0x2c, 0xa4, 0xf2, 0x66, 0x3e, 0xe6, 0x80, 0x66,
	0x4f, 0xb2, 0x90, 0xa2, 0x6b, 0xf0, 0x1c, 0x89, 0x29, 0xe6, 0xd4, 0xb6, 0x30, 0xb7, 0x5c, 0xea,
	0x39, 0x2e, 0x97, 0x4b, 0x55, 0xd0, 0x58, 0x37, 0xcf, 0xce, 0x02, 0x2d, 0x7e, 0x5f, 0xc8, 0xe8,
	0x26, 0x2c, 0xfb, 0x9e, 0x13, 0x0b, 0xbb, 0xac, 0x85, 0xe5, 0xb6, 0x04, 0x11, 0x15, 0x31, 0xa3,
	0xd8, 0xf2, 0x36, 0xbc, 0x30, 0xaf, 0x58, 0xda, 0x77, 0x5b, 0xec, 0x3b, 0xef, 0xd7, 0x9a, 0x2f,
	0x7e, 0xf4, 0x0e, 0xc0, 0x0d, 0x61, 0x29, 0x7a, 0x0b, 0x60, 0x69, 0xf6, 0xbb, 0x51, 0x7d, 0xd5,
	0xa8, 0xbf, 0x1c, 0xca, 0xe1, 0xd5, 0xff, 0xa5, 0xe5, 0xe7, 0x51, 0xbb, 0xfe, 0xe6, 0xeb, 0x8f,
	0x0f, 0x52, 0x1d, 0x5d, 0xd1, 0x56, 0xce, 0x77, 0xe6, 0xb7, 0xf6, 0x6a, 0xe6, 0xe5, 0xeb, 0xf6,
	0x6f, 0xf0, 0x79, 0xac, 0x80, 0xe3, 0xb1, 0x02, 0xbe, 0x8f, 0x15, 0xf0, 0x7e, 0xa2, 0xac, 0x1d,
	0x4f, 0x94, 0xb5, 0x6f, 0x13, 0x65, 0x0d, 0x96, 0x09, 0xf3, 0x57, 0x90, 0x6d, 0x28, 0x98, 0xc6,
	0xf4, 0xa2, 0x0d, 0xf0, 0xfc, 0xa9, 0xe3, 0x71, 0x37, 0xed, 0xab, 0x84, 0xf9, 0x0b, 0xb4, 0xe2,
	0xeb, 0x46, 0x62, 0x0f, 0xb4, 0x10, 0x93, 0x01, 0x76, 0x68, 0xa2, 0x39, 0x6c, 0x71, 0xa2, 0x69,
	0x87, 0x95, 0x09, 0xef, 0x84, 0x11, 0x19, 0xe9, 0x1f, 0xa5, 0xf5, 0x8e, 0xf1, 0xec, 0x93, 0x74,
	0xd0, 0x29, 0xe8, 0x46, 0x44, 0xd4, 0xae, 0xfe, 0x65, 0x41, 0xea, 0x19, 0x11, 0xe9, 0x75, 0xf5,
	0xb1, 0x54, 0x39, 0x2d, 0xf5, 0xee, 0x19, 0xed, 0x47, 0x94, 0x63, 0x1b, 0x73, 0xfc, 0x4b, 0x42,
	0x45, 0xb8, 0xd9, 0x34, 0x22, 0xd2, 0x6c, 0x76, 0xf5, 0xfe, 0xa6, 0xa0, 0xdf, 0xfa, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x22, 0xf1, 0x39, 0x6e, 0xe1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Account returns the registered PQC key information for an address.
	Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error) {
	out := new(QueryAccountResponse)
	err := c.cc.Invoke(ctx, "/qorechain.pqc.v1.Query/Account", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Account returns the registered PQC key information for an address.
	Account(context.Context, *QueryAccountRequest) (*QueryAccountResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Account(ctx context.Context, req *QueryAccountRequest) (*QueryAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Account not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.pqc.v1.Query/Account",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Account(ctx, req.(*QueryAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.pqc.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Account",
			Handler:    _Query_Account_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/pqc/v1/query.proto",
}

func (m *QueryAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Account != nil {
		{
			size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PQCAccountView) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PQCAccountView) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PQCAccountView) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MigrationAlgorithmId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MigrationAlgorithmId))
		i--
		dAtA[i] = 0x48
	}
	if len(m.MigrationPublicKey) > 0 {
		i -= len(m.MigrationPublicKey)
		copy(dAtA[i:], m.MigrationPublicKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MigrationPublicKey)))
		i--
		dAtA[i] = 0x42
	}
	if m.CreatedAtHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CreatedAtHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.KeyType) > 0 {
		i -= len(m.KeyType)
		copy(dAtA[i:], m.KeyType)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.KeyType)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EcdsaPubkey) > 0 {
		i -= len(m.EcdsaPubkey)
		copy(dAtA[i:], m.EcdsaPubkey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EcdsaPubkey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AlgorithmName) > 0 {
		i -= len(m.AlgorithmName)
		copy(dAtA[i:], m.AlgorithmName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AlgorithmName)))
		i--
		dAtA[i] = 0x22
	}
	if m.AlgorithmId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AlgorithmId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Found {
		n += 2
	}
	if m.Account != nil {
		l = m.Account.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *PQCAccountView) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AlgorithmId != 0 {
		n += 1 + sovQuery(uint64(m.AlgorithmId))
	}
	l = len(m.AlgorithmName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.EcdsaPubkey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.KeyType)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CreatedAtHeight != 0 {
		n += 1 + sovQuery(uint64(m.CreatedAtHeight))
	}
	l = len(m.MigrationPublicKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.MigrationAlgorithmId != 0 {
		n += 1 + sovQuery(uint64(m.MigrationAlgorithmId))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Account == nil {
				m.Account = &PQCAccountView{}
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PQCAccountView) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PQCAccountView: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PQCAccountView: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlgorithmId", wireType)
			}
			m.AlgorithmId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AlgorithmId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlgorithmName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AlgorithmName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcdsaPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EcdsaPubkey = append(m.EcdsaPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.EcdsaPubkey == nil {
				m.EcdsaPubkey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtHeight", wireType)
			}
			m.CreatedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MigrationPublicKey = append(m.MigrationPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.MigrationPublicKey == nil {
				m.MigrationPublicKey = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationAlgorithmId", wireType)
			}
			m.MigrationAlgorithmId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MigrationAlgorithmId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
