// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qorechain/pqc/v1/query.proto

package pqcv1

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryEVMWindowRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryEVMWindowRequest) Reset()         { *m = QueryEVMWindowRequest{} }
func (m *QueryEVMWindowRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEVMWindowRequest) ProtoMessage()    {}
func (*QueryEVMWindowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{0}
}
func (m *QueryEVMWindowRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEVMWindowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEVMWindowRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEVMWindowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEVMWindowRequest.Merge(m, src)
}
func (m *QueryEVMWindowRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEVMWindowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEVMWindowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEVMWindowRequest proto.InternalMessageInfo

func (m *QueryEVMWindowRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryEVMWindowResponse struct {
	// found reports whether a window is stored. A stored window may still be
	// exhausted or expired; check live.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// live reports whether the window admits at least one more transaction of
	// zero value at the current height.
	Live         bool   `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
	OpenedHeight uint64 `protobuf:"varint,3,opt,name=opened_height,json=openedHeight,proto3" json:"opened_height,omitempty"`
	ExpiryHeight uint64 `protobuf:"varint,4,opt,name=expiry_height,json=expiryHeight,proto3" json:"expiry_height,omitempty"`
	MaxTxs       uint64 `protobuf:"varint,5,opt,name=max_txs,json=maxTxs,proto3" json:"max_txs,omitempty"`
	UsedTxs      uint64 `protobuf:"varint,6,opt,name=used_txs,json=usedTxs,proto3" json:"used_txs,omitempty"`
	MaxValue     string `protobuf:"bytes,7,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	UsedValue    string `protobuf:"bytes,8,opt,name=used_value,json=usedValue,proto3" json:"used_value,omitempty"`
	// remaining_blocks, remaining_txs and remaining_value say which bound is
	// closest to running out, so a refused caller can tell why.
	RemainingBlocks uint64 `protobuf:"varint,9,opt,name=remaining_blocks,json=remainingBlocks,proto3" json:"remaining_blocks,omitempty"`
	RemainingTxs    uint64 `protobuf:"varint,10,opt,name=remaining_txs,json=remainingTxs,proto3" json:"remaining_txs,omitempty"`
	RemainingValue  string `protobuf:"bytes,11,opt,name=remaining_value,json=remainingValue,proto3" json:"remaining_value,omitempty"`
}

func (m *QueryEVMWindowResponse) Reset()         { *m = QueryEVMWindowResponse{} }
func (m *QueryEVMWindowResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEVMWindowResponse) ProtoMessage()    {}
func (*QueryEVMWindowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{1}
}
func (m *QueryEVMWindowResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEVMWindowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEVMWindowResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEVMWindowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEVMWindowResponse.Merge(m, src)
}
func (m *QueryEVMWindowResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEVMWindowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEVMWindowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEVMWindowResponse proto.InternalMessageInfo

func (m *QueryEVMWindowResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *QueryEVMWindowResponse) GetLive() bool {
	if m != nil {
		return m.Live
	}
	return false
}

func (m *QueryEVMWindowResponse) GetOpenedHeight() uint64 {
	if m != nil {
		return m.OpenedHeight
	}
	return 0
}

func (m *QueryEVMWindowResponse) GetExpiryHeight() uint64 {
	if m != nil {
		return m.ExpiryHeight
	}
	return 0
}

func (m *QueryEVMWindowResponse) GetMaxTxs() uint64 {
	if m != nil {
		return m.MaxTxs
	}
	return 0
}

func (m *QueryEVMWindowResponse) GetUsedTxs() uint64 {
	if m != nil {
		return m.UsedTxs
	}
	return 0
}

func (m *QueryEVMWindowResponse) GetMaxValue() string {
	if m != nil {
		return m.MaxValue
	}
	return ""
}

func (m *QueryEVMWindowResponse) GetUsedValue() string {
	if m != nil {
		return m.UsedValue
	}
	return ""
}

func (m *QueryEVMWindowResponse) GetRemainingBlocks() uint64 {
	if m != nil {
		return m.RemainingBlocks
	}
	return 0
}

func (m *QueryEVMWindowResponse) GetRemainingTxs() uint64 {
	if m != nil {
		return m.RemainingTxs
	}
	return 0
}

func (m *QueryEVMWindowResponse) GetRemainingValue() string {
	if m != nil {
		return m.RemainingValue
	}
	return ""
}

type QueryAccountRequest struct {
	// address is the bech32 account address whose PQC key is requested.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAccountRequest) Reset()         { *m = QueryAccountRequest{} }
func (m *QueryAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAccountRequest) ProtoMessage()    {}
func (*QueryAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{2}
}
func (m *QueryAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountRequest.Merge(m, src)
}
func (m *QueryAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountRequest proto.InternalMessageInfo

func (m *QueryAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAccountResponse struct {
	// found reports whether the account has a registered PQC key.
	Found   bool            `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Account *PQCAccountView `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *QueryAccountResponse) Reset()         { *m = QueryAccountResponse{} }
func (m *QueryAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAccountResponse) ProtoMessage()    {}
func (*QueryAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{3}
}
func (m *QueryAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountResponse.Merge(m, src)
}
func (m *QueryAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountResponse proto.InternalMessageInfo

func (m *QueryAccountResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *QueryAccountResponse) GetAccount() *PQCAccountView {
	if m != nil {
		return m.Account
	}
	return nil
}

// PQCAccountView is the query-facing view of a registered PQC account.
type PQCAccountView struct {
	Address              string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey            []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AlgorithmId          uint32 `protobuf:"varint,3,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmName        string `protobuf:"bytes,4,opt,name=algorithm_name,json=algorithmName,proto3" json:"algorithm_name,omitempty"`
	EcdsaPubkey          []byte `protobuf:"bytes,5,opt,name=ecdsa_pubkey,json=ecdsaPubkey,proto3" json:"ecdsa_pubkey,omitempty"`
	KeyType              string `protobuf:"bytes,6,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	CreatedAtHeight      int64  `protobuf:"varint,7,opt,name=created_at_height,json=createdAtHeight,proto3" json:"created_at_height,omitempty"`
	MigrationPublicKey   []byte `protobuf:"bytes,8,opt,name=migration_public_key,json=migrationPublicKey,proto3" json:"migration_public_key,omitempty"`
	MigrationAlgorithmId uint32 `protobuf:"varint,9,opt,name=migration_algorithm_id,json=migrationAlgorithmId,proto3" json:"migration_algorithm_id,omitempty"`
}

func (m *PQCAccountView) Reset()         { *m = PQCAccountView{} }
func (m *PQCAccountView) String() string { return proto.CompactTextString(m) }
func (*PQCAccountView) ProtoMessage()    {}
func (*PQCAccountView) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f221b60dbf809b5, []int{4}
}
func (m *PQCAccountView) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PQCAccountView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PQCAccountView.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PQCAccountView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PQCAccountView.Merge(m, src)
}
func (m *PQCAccountView) XXX_Size() int {
	return m.Size()
}
func (m *PQCAccountView) XXX_DiscardUnknown() {
	xxx_messageInfo_PQCAccountView.DiscardUnknown(m)
}

var xxx_messageInfo_PQCAccountView proto.InternalMessageInfo

func (m *PQCAccountView) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PQCAccountView) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *PQCAccountView) GetAlgorithmId() uint32 {
	if m != nil {
		return m.AlgorithmId
	}
	return 0
}

func (m *PQCAccountView) GetAlgorithmName() string {
	if m != nil {
		return m.AlgorithmName
	}
	return ""
}

func (m *PQCAccountView) GetEcdsaPubkey() []byte {
	if m != nil {
		return m.EcdsaPubkey
	}
	return nil
}

func (m *PQCAccountView) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *PQCAccountView) GetCreatedAtHeight() int64 {
	if m != nil {
		return m.CreatedAtHeight
	}
	return 0
}

func (m *PQCAccountView) GetMigrationPublicKey() []byte {
	if m != nil {
		return m.MigrationPublicKey
	}
	return nil
}

func (m *PQCAccountView) GetMigrationAlgorithmId() uint32 {
	if m != nil {
		return m.MigrationAlgorithmId
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryEVMWindowRequest)(nil), "qorechain.pqc.v1.QueryEVMWindowRequest")
	proto.RegisterType((*QueryEVMWindowResponse)(nil), "qorechain.pqc.v1.QueryEVMWindowResponse")
	proto.RegisterType((*QueryAccountRequest)(nil), "qorechain.pqc.v1.QueryAccountRequest")
	proto.RegisterType((*QueryAccountResponse)(nil), "qorechain.pqc.v1.QueryAccountResponse")
	proto.RegisterType((*PQCAccountView)(nil), "qorechain.pqc.v1.PQCAccountView")
}

func init() { proto.RegisterFile("qorechain/pqc/v1/query.proto", fileDescriptor_0f221b60dbf809b5) }

var fileDescriptor_0f221b60dbf809b5 = []byte{
	// 787 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xdb, 0x46,
	0x14, 0x34, 0x69, 0xcb, 0x12, 0x57, 0xfe, 0xea, 0x56, 0x75, 0x55, 0xd7, 0x15, 0x5c, 0x19, 0xb6,
	0xd5, 0x16, 0x25, 0x2b, 0xb7, 0x27, 0xf5, 0x64, 0x15, 0x45, 0x5b, 0x14, 0x0e, 0x28, 0xc2, 0x51,
	0x82, 0xc0, 0x00, 0xb1, 0x5a, 0x6e, 0x28, 0x42, 0x22, 0x97, 0x9f, 0xb2, 0x88, 0x20, 0x97, 0x00,
	0xb9, 0x06, 0x01, 0xf2, 0x07, 0x82, 0x1c, 0xf3, 0x4b, 0x82, 0x9c, 0x0c, 0xe4, 0x92, 0x63, 0x20,
	0x27, 0x97, 0x5c, 0x83, 0xdc, 0x83, 0x5d, 0x52, 0x94, 0x2c, 0xc5, 0xf1, 0x4d, 0x3b, 0x33, 0x6f,
	0x67, 0x1e, 0xdf, 0xd3, 0x82, 0x6d, 0x8f, 0xfa, 0x04, 0x77, 0x91, 0xe5, 0x28, 0xae, 0x87, 0x95,
	0x41, 0x5d, 0xf1, 0x22, 0xe2, 0xc7, 0xb2, 0xeb, 0xd3, 0x90, 0xc2, 0x8d, 0x8c, 0x95, 0x5d, 0x0f,
	0xcb, 0x83, 0xfa, 0xd6, 0xb6, 0x49, 0xa9, 0xd9, 0x27, 0x0a, 0x72, 0x2d, 0x05, 0x39, 0x0e, 0x0d,
	0x51, 0x68, 0x51, 0x27, 0x48, 0xf4, 0xd5, 0x3a, 0xf8, 0xa6, 0xc5, 0xca, 0xff, 0x6e, 0x1f, 0xdf,
	0xb2, 0x1c, 0x83, 0x9e, 0x69, 0xc4, 0x8b, 0x48, 0x10, 0xc2, 0x32, 0xc8, 0x23, 0xc3, 0xf0, 0x49,
	0x10, 0x94, 0x85, 0x1d, 0xa1, 0x26, 0x69, 0xe3, 0x63, 0xf5, 0xa3, 0x08, 0x36, 0x67, 0x6b, 0x02,
	0x97, 0x3a, 0x01, 0x81, 0x25, 0x90, 0xbb, 0x4b, 0x23, 0xc7, 0xe0, 0x25, 0x05, 0x2d, 0x39, 0x40,
	0x08, 0x96, 0xfa, 0xd6, 0x80, 0x94, 0x45, 0x0e, 0xf2, 0xdf, 0x70, 0x17, 0xac, 0x52, 0x97, 0x38,
	0xc4, 0xd0, 0xbb, 0xc4, 0x32, 0xbb, 0x61, 0x79, 0x71, 0x47, 0xa8, 0x2d, 0x69, 0x2b, 0x09, 0xf8,
	0x2f, 0xc7, 0x98, 0x88, 0x0c, 0x5d, 0xcb, 0x8f, 0xc7, 0xa2, 0xa5, 0x44, 0x94, 0x80, 0xa9, 0xe8,
	0x5b, 0x90, 0xb7, 0xd1, 0x50, 0x0f, 0x87, 0x41, 0x39, 0xc7, 0xe9, 0x65, 0x1b, 0x0d, 0x4f, 0x86,
	0x01, 0xfc, 0x0e, 0x14, 0xa2, 0x80, 0x18, 0x9c, 0x59, 0xe6, 0x4c, 0x9e, 0x9d, 0x19, 0xf5, 0x3d,
	0x90, 0x58, 0xcd, 0x00, 0xf5, 0x23, 0x52, 0xce, 0xf3, 0xf6, 0x0a, 0x36, 0x1a, 0xb6, 0xd9, 0x19,
	0xfe, 0x00, 0x00, 0xaf, 0x4b, 0xd8, 0x02, 0x67, 0x25, 0x86, 0x24, 0xf4, 0x4f, 0x60, 0xc3, 0x27,
	0x36, 0xb2, 0x1c, 0xcb, 0x31, 0xf5, 0x4e, 0x9f, 0xe2, 0x5e, 0x50, 0x96, 0xf8, 0xf5, 0xeb, 0x19,
	0xde, 0xe4, 0x30, 0xcb, 0x3f, 0x91, 0xb2, 0x18, 0x20, 0xc9, 0x9f, 0x81, 0x2c, 0xcb, 0x01, 0x98,
	0xd4, 0xa5, 0x9e, 0x45, 0xee, 0xb9, 0x96, 0xc1, 0xdc, 0xb8, 0xaa, 0x80, 0xaf, 0xf9, 0x67, 0x3f,
	0xc2, 0x98, 0x46, 0x4e, 0x78, 0xfd, 0xa0, 0xba, 0xa0, 0x74, 0xb9, 0xe0, 0x8b, 0x53, 0x6a, 0x80,
	0x3c, 0x4a, 0x84, 0x7c, 0x50, 0xc5, 0xc3, 0x1d, 0x79, 0x76, 0x97, 0x64, 0xb5, 0xf5, 0x57, 0x7a,
	0x59, 0xdb, 0x22, 0x67, 0xda, 0xb8, 0xa0, 0xfa, 0x4e, 0x04, 0x6b, 0x97, 0xb9, 0xab, 0x63, 0xb1,
	0xef, 0xeb, 0x46, 0x9d, 0xbe, 0x85, 0xf5, 0x1e, 0x89, 0xb9, 0xd7, 0x8a, 0x26, 0x25, 0xc8, 0xff,
	0x24, 0x86, 0x3f, 0x82, 0x15, 0xd4, 0x37, 0xa9, 0x6f, 0x85, 0x5d, 0x5b, 0xb7, 0x0c, 0xbe, 0x18,
	0xab, 0x5a, 0x31, 0xc3, 0xfe, 0x33, 0xe0, 0x1e, 0x58, 0x9b, 0x48, 0x1c, 0x64, 0x13, 0xbe, 0x18,
	0x92, 0xb6, 0x9a, 0xa1, 0x37, 0x90, 0x4d, 0xd8, 0x4d, 0x04, 0x1b, 0x01, 0xd2, 0xdd, 0xa8, 0xc3,
	0xac, 0x72, 0xdc, 0xaa, 0xc8, 0x31, 0x95, 0x43, 0x6c, 0x47, 0x7a, 0x24, 0xd6, 0xc3, 0xd8, 0x25,
	0x7c, 0x47, 0x24, 0x2d, 0xdf, 0x23, 0xf1, 0x49, 0xec, 0x12, 0xf8, 0x33, 0xf8, 0x0a, 0xfb, 0x04,
	0x85, 0xc4, 0xd0, 0x51, 0x38, 0x5e, 0x40, 0xb6, 0x2b, 0x8b, 0xda, 0x7a, 0x4a, 0x1c, 0x85, 0xe9,
	0x0e, 0xfe, 0x06, 0x4a, 0xb6, 0x65, 0xfa, 0xfc, 0x9f, 0xa5, 0x4f, 0x35, 0x57, 0xe0, 0x8e, 0x30,
	0xe3, 0xd4, 0xac, 0xcb, 0x3f, 0xc0, 0xe6, 0xa4, 0xe2, 0x52, 0xbf, 0x12, 0xef, 0x77, 0x72, 0xdf,
	0xd1, 0xa4, 0xf1, 0xc3, 0xa7, 0x22, 0xc8, 0xf1, 0x91, 0xc2, 0x87, 0x02, 0xc8, 0xa7, 0x9f, 0x1b,
	0xee, 0xcd, 0x0f, 0xea, 0x33, 0x8b, 0xb2, 0xb5, 0x7f, 0x9d, 0x2c, 0x59, 0x8f, 0xea, 0x2f, 0x0f,
	0x5e, 0xbd, 0x7d, 0x22, 0xee, 0xc1, 0x5d, 0x65, 0xee, 0xa5, 0x49, 0xe7, 0xad, 0xdc, 0x4b, 0x67,
	0x79, 0x1f, 0x3e, 0x12, 0x80, 0x94, 0xbd, 0x03, 0xf0, 0xe0, 0x0a, 0x8b, 0xd9, 0xd7, 0x65, 0xab,
	0x76, 0xbd, 0x30, 0x4d, 0x23, 0xf3, 0x34, 0x35, 0xb8, 0x3f, 0x9f, 0x86, 0x0c, 0x6c, 0xfd, 0x8c,
	0xab, 0x27, 0x81, 0x9a, 0x1f, 0x84, 0x17, 0xa3, 0x8a, 0x70, 0x3e, 0xaa, 0x08, 0x6f, 0x46, 0x15,
	0xe1, 0xf1, 0x45, 0x65, 0xe1, 0xfc, 0xa2, 0xb2, 0xf0, 0xfa, 0xa2, 0xb2, 0x00, 0x4a, 0x98, 0xda,
	0x73, 0xbe, 0x4d, 0xc0, 0x8d, 0x55, 0xf6, 0x1a, 0xaa, 0xc2, 0x9d, 0x9b, 0xa6, 0x15, 0x76, 0xa3,
	0x8e, 0x8c, 0xa9, 0x3d, 0x65, 0x98, 0xfd, 0xfa, 0x35, 0x30, 0x7a, 0x8a, 0x8b, 0x70, 0x0f, 0x99,
	0x24, 0x50, 0x4c, 0x3a, 0x1d, 0x8a, 0xdd, 0x30, 0x17, 0xf2, 0x4f, 0xd7, 0xc3, 0x83, 0xfa, 0x33,
	0x71, 0xb1, 0xa5, 0xde, 0x7e, 0x2e, 0x6e, 0xb4, 0x32, 0x77, 0xd5, 0xc3, 0x72, 0xbb, 0xfe, 0x72,
	0x0a, 0x3a, 0x55, 0x3d, 0x7c, 0xda, 0xae, 0x8f, 0xc4, 0xed, 0x59, 0xe8, 0xf4, 0x1f, 0xb5, 0x79,
	0x4c, 0x42, 0x64, 0xa0, 0x10, 0xbd, 0x17, 0x61, 0x46, 0x37, 0x1a, 0xaa, 0x87, 0x1b, 0x8d, 0x76,
	0xbd, 0xb3, 0xcc, 0xdd, 0x7f, 0xff, 0x14, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x8a, 0x5d, 0x65, 0x1d,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Account returns the registered PQC key information for an address.
	Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error)
	// EVMWindow returns an address's open EVM-lane authorisation window, if any,
	// with what remains of it at the current height.
	EVMWindow(ctx context.Context, in *QueryEVMWindowRequest, opts ...grpc.CallOption) (*QueryEVMWindowResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error) {
	out := new(QueryAccountResponse)
	err := c.cc.Invoke(ctx, "/qorechain.pqc.v1.Query/Account", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EVMWindow(ctx context.Context, in *QueryEVMWindowRequest, opts ...grpc.CallOption) (*QueryEVMWindowResponse, error) {
	out := new(QueryEVMWindowResponse)
	err := c.cc.Invoke(ctx, "/qorechain.pqc.v1.Query/EVMWindow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Account returns the registered PQC key information for an address.
	Account(context.Context, *QueryAccountRequest) (*QueryAccountResponse, error)
	// EVMWindow returns an address's open EVM-lane authorisation window, if any,
	// with what remains of it at the current height.
	EVMWindow(context.Context, *QueryEVMWindowRequest) (*QueryEVMWindowResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Account(ctx context.Context, req *QueryAccountRequest) (*QueryAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Account not implemented")
}
func (*UnimplementedQueryServer) EVMWindow(ctx context.Context, req *QueryEVMWindowRequest) (*QueryEVMWindowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EVMWindow not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.pqc.v1.Query/Account",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Account(ctx, req.(*QueryAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EVMWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEVMWindowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EVMWindow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qorechain.pqc.v1.Query/EVMWindow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EVMWindow(ctx, req.(*QueryEVMWindowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qorechain.pqc.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Account",
			Handler:    _Query_Account_Handler,
		},
		{
			MethodName: "EVMWindow",
			Handler:    _Query_EVMWindow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qorechain/pqc/v1/query.proto",
}

func (m *QueryEVMWindowRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEVMWindowRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEVMWindowRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEVMWindowResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEVMWindowResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEVMWindowResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RemainingValue) > 0 {
		i -= len(m.RemainingValue)
		copy(dAtA[i:], m.RemainingValue)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RemainingValue)))
		i--
		dAtA[i] = 0x5a
	}
	if m.RemainingTxs != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RemainingTxs))
		i--
		dAtA[i] = 0x50
	}
	if m.RemainingBlocks != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.RemainingBlocks))
		i--
		dAtA[i] = 0x48
	}
	if len(m.UsedValue) > 0 {
		i -= len(m.UsedValue)
		copy(dAtA[i:], m.UsedValue)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UsedValue)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.MaxValue) > 0 {
		i -= len(m.MaxValue)
		copy(dAtA[i:], m.MaxValue)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MaxValue)))
		i--
		dAtA[i] = 0x3a
	}
	if m.UsedTxs != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.UsedTxs))
		i--
		dAtA[i] = 0x30
	}
	if m.MaxTxs != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MaxTxs))
		i--
		dAtA[i] = 0x28
	}
	if m.ExpiryHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ExpiryHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.OpenedHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.OpenedHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.Live {
		i--
		if m.Live {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Account != nil {
		{
			size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Found {
		i--
		if m.Found {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PQCAccountView) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PQCAccountView) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PQCAccountView) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MigrationAlgorithmId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.MigrationAlgorithmId))
		i--
		dAtA[i] = 0x48
	}
	if len(m.MigrationPublicKey) > 0 {
		i -= len(m.MigrationPublicKey)
		copy(dAtA[i:], m.MigrationPublicKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MigrationPublicKey)))
		i--
		dAtA[i] = 0x42
	}
	if m.CreatedAtHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.CreatedAtHeight))
		i--
		dAtA[i] = 0x38
	}
	if len(m.KeyType) > 0 {
		i -= len(m.KeyType)
		copy(dAtA[i:], m.KeyType)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.KeyType)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.EcdsaPubkey) > 0 {
		i -= len(m.EcdsaPubkey)
		copy(dAtA[i:], m.EcdsaPubkey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.EcdsaPubkey)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AlgorithmName) > 0 {
		i -= len(m.AlgorithmName)
		copy(dAtA[i:], m.AlgorithmName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AlgorithmName)))
		i--
		dAtA[i] = 0x22
	}
	if m.AlgorithmId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.AlgorithmId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryEVMWindowRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEVMWindowResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Found {
		n += 2
	}
	if m.Live {
		n += 2
	}
	if m.OpenedHeight != 0 {
		n += 1 + sovQuery(uint64(m.OpenedHeight))
	}
	if m.ExpiryHeight != 0 {
		n += 1 + sovQuery(uint64(m.ExpiryHeight))
	}
	if m.MaxTxs != 0 {
		n += 1 + sovQuery(uint64(m.MaxTxs))
	}
	if m.UsedTxs != 0 {
		n += 1 + sovQuery(uint64(m.UsedTxs))
	}
	l = len(m.MaxValue)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.UsedValue)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.RemainingBlocks != 0 {
		n += 1 + sovQuery(uint64(m.RemainingBlocks))
	}
	if m.RemainingTxs != 0 {
		n += 1 + sovQuery(uint64(m.RemainingTxs))
	}
	l = len(m.RemainingValue)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Found {
		n += 2
	}
	if m.Account != nil {
		l = m.Account.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *PQCAccountView) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.AlgorithmId != 0 {
		n += 1 + sovQuery(uint64(m.AlgorithmId))
	}
	l = len(m.AlgorithmName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.EcdsaPubkey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.KeyType)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.CreatedAtHeight != 0 {
		n += 1 + sovQuery(uint64(m.CreatedAtHeight))
	}
	l = len(m.MigrationPublicKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.MigrationAlgorithmId != 0 {
		n += 1 + sovQuery(uint64(m.MigrationAlgorithmId))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryEVMWindowRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEVMWindowRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEVMWindowRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEVMWindowResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEVMWindowResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEVMWindowResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Live", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Live = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenedHeight", wireType)
			}
			m.OpenedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpenedHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryHeight", wireType)
			}
			m.ExpiryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTxs", wireType)
			}
			m.MaxTxs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxTxs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedTxs", wireType)
			}
			m.UsedTxs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UsedTxs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UsedValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UsedValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingBlocks", wireType)
			}
			m.RemainingBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingTxs", wireType)
			}
			m.RemainingTxs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RemainingTxs |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemainingValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemainingValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Found", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Found = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Account == nil {
				m.Account = &PQCAccountView{}
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PQCAccountView) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PQCAccountView: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PQCAccountView: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlgorithmId", wireType)
			}
			m.AlgorithmId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AlgorithmId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AlgorithmName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AlgorithmName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EcdsaPubkey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EcdsaPubkey = append(m.EcdsaPubkey[:0], dAtA[iNdEx:postIndex]...)
			if m.EcdsaPubkey == nil {
				m.EcdsaPubkey = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field KeyType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.KeyType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtHeight", wireType)
			}
			m.CreatedAtHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MigrationPublicKey = append(m.MigrationPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.MigrationPublicKey == nil {
				m.MigrationPublicKey = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationAlgorithmId", wireType)
			}
			m.MigrationAlgorithmId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MigrationAlgorithmId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
